### ISSUE TITLE
Floccus deleted a bookmark

### ISSUE THREAD

**Issue by SlaveOfCats** [floccusaddon/floccus#1245] opened 2022-09-01 22:45 UTC
### Which version of floccus are you using?

4.17.0

### Sync method

WebDAV

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Firefox 101.0.1, 91.11.0 ESR

### Which version of Nextcloud? (if relevant)

23.0.7

### What kind of WebDAV server are you using? (if relevant)

Using Nextcloud as WebDAV server

### Describe the Bug

I installed floccus on 3 installations of Firefox. All are configured to merge bookmarks. One FF had the following bookmark:

`chrome://global/content/config.xhtml`

After syncing, this bookmark was gone and did not appear in the other two FF installations. Then I manually added it to one installation that did not originally have the bookmark. After the next sync, it was gone.

### Expected Behavior

Floccus should not delete a bookmark, even if for some reason it won't sync it.

### To Reproduce

Add this bookmark to Firefox: `chrome://global/content/config.xhtml`

Merge bookmarks with another FF installation. 

Bookmark will be removed.

### Debug log provided

- [ ] I have provided a debug log file

**Comment by marcelklehr** [comment] 2023-03-22 09:43
> Merge bookmarks with another FF installation.

What does this mean? Merge sync with floccus?

Following these steps, I cannot reproduce this:

1. Add this bookmark to Firefox: chrome://global/content/config.xhtml
2. Run merge sync with floccus

Result: Bookmark is still there.

**Comment by SlaveOfCats** [comment] 2023-03-26 15:49
Yes, "merge bookmarks" meant merge sync with floccus.

I just retested with floccus version 4.19.0 and the problem seems to be gone. The bookmark is not deleted and it is also not merged, which I think is expected for a chrome bookmark.

**Comment by marcelklehr** [comment] 2023-03-26 15:56
> I just retested with floccus version 4.19.0 and the problem seems to be gone.

Cool! Thanks for getting back to me! Closing this then :)

**Closed by marcelklehr** 2023-03-26 15:56 UTC
Labels: bug, waiting for more information
