### ISSUE TITLE
Floccus, Android (from F-Droid) freeze at start on Graphene OS

### ISSUE THREAD

**Issue by Schneehexe** [floccusaddon/floccus#1513] opened 2024-01-05 15:13 UTC
### Which version of floccus are you using?

5.0.6

### Sync method

Nextcloud Bookmarks

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Firefox on Windows PC

### Which version of Nextcloud Bookmarks are you using? (if relevant)

13.1.3

### Which version of Nextcloud? (if relevant)

27.1.5

### Describe the Bug

I start Floccus on the Pixel 7 pro 256, Graphene OS, Android14. The app starts partially so that I can see the intro screen, i.e. the white circle with the blue cloud and a tick in it. After that, nothing happens.

Before the last Floccus update, however, the transfer still worked perfectly.

Just for further information, I have restarted the device and also uninstalled and reinstalled Floccus for Android - but it shows the same behavior.

### Expected Behavior

Floccus for Android starts and I can manage and select bookmarks in Floccus

### To Reproduce

Starting Floccus as described

### Debug log provided

- [ ] I have provided a debug log file

**Comment by marcelklehr** [comment] 2024-01-05 15:35
Duplicate of #1508 
v5.0.7 fixes this, will be available soon :blue_heart:

**Closed by marcelklehr** 2024-01-05 15:35 UTC
Labels: bug
