### ISSUE TITLE
why Synchronization strategy changes itself for Chromium

### ISSUE THREAD

**Issue by candrapersada** [floccusaddon/floccus#848] opened 2021-03-07 10:24 UTC
### Describe the bug
why Synchronization strategy changes itself from Always revert upstream remote changes and push local changes to Merge local and remote changes (recommended) when I sync manually

### To Reproduce
1. Go to 'floccus'
2. Click on 'Sync up'

### Expected behavior
Synchronization strategy tabs settings change when manually syncing

### Desktop
 - OS: Windows 10 Home
 - Browser Firefox and Chromium
 - Floccus version: 4.6.1
 - Floccus sync method: Google Drive

**Comment by marcelklehr** [comment] 2021-03-07 10:56
Confirmed.

**Comment by marcelklehr** [comment] 2021-03-07 10:57
Fixed. Will be released soon. Thanks for reporting :blush:

**Comment by candrapersada** [comment] 2021-03-13 23:41
The time between two synchronizations runs in a few minutes. The default is 15 minutes. does not work when the browser starts
for example when I start the browser after 1 day the sync immediately starts before 15 minutes why can this happen?

**Comment by marcelklehr** [comment] 2021-03-17 14:01
> for example when I start the browser after 1 day close the sync starts immediately before 15 minutes why this happens?

This is because floccus calculates the time between sync runs. If the last sync run was more than 15min ago, it will run a sync, even if the browser was just started.

**Comment by marcelklehr** [comment] 2021-03-17 14:01
I cannot reproduce this issue anymore with v4.6.1. Can you make sure you are running this latest version?

**Comment by candrapersada** [comment] 2021-03-17 17:46
> I cannot reproduce this issue anymore with v4.6.1. Can you make sure you are running this latest version?

yes this is the latest version.

**Comment by candrapersada** [comment] 2021-03-19 06:22
the problem is in chromium.

**Comment by marcelklehr** [comment] 2021-03-19 12:26
I cannot reproduce this in Chromium either.

This is what I tried:

1. Create Google Drive sync Account
2. set push sync strategy
3. click push sync / pull sync / normal sync in overview panel
4. refresh account settings
5. sync strategy is still push sync

What did you do?

**Comment by candrapersada** [comment] 2021-03-19 18:43
but the sync strategy still changes itself for tabs chromium. from push sync changes to pull sync when pull sync manually.

**Comment by marcelklehr** [comment] 2021-03-19 19:09
Aha. For tabs. I'll try that.

**Comment by candrapersada** [comment] 2021-03-19 19:10
after importing configurations from floccus v4.6.0 to v4.6.1

**Comment by marcelklehr** [comment] 2021-03-20 12:12
This only happens when opening settings while the pull sync is running. When sync strategy is set to push, and you manually pull, the strategy is temporarily changed to pull, until after the sync run, when it is reset to push. This is by design.

**Closed by marcelklehr** 2021-03-20 12:12 UTC
Labels: bug

**Comment by candrapersada** [comment] 2021-03-20 19:00
but why only happens for chromium tabs?
