### ISSUE TITLE
Syncing tabs removes bookmarks with same name in different folders 

### ISSUE THREAD

**Issue by mnalis** [floccusaddon/floccus#912] opened 2021-07-14 18:53 UTC
### Describe the bug
I have 3 different sync "Accounts" setup: `Tabs`, `Bookmarks Toolbar`, `Bookmarks Menu` which sync to **different** folders on nextcloud bookmarks (using same account/password). What happens is when `Tabs` are trying to sync (and fail due to https://github.com/floccusaddon/floccus/issues/883) it also removes bookmarks with same URL from my `Bookmarks Toolbar` (and possibly `Bookmarks Menu`, have to do detailed comparison with backup). 

Final effect is that any tabs I have open (or maybe only those I have open in multiple tabs?) are silently removed from all my bookmarks, which is bad. 

When I disable syncing `Tabs`, problem disappears.

### To Reproduce
1. Click `New account`, set nextcloud sync with `Local Folder=/Bookmarks Menu/`, `Server Folder=/book_main`
2. Click `New account`, set nextcloud sync with `Local Folder=/Bookmarks Toolbar/`, `Server Folder=/book_toolbar`
3. Click `New account`, set nextcloud sync with `Sync Tabs`, `Server Folder=/tabs_leia`
4. Have many tabs open, some of which are from Bookmarks Toolbar
5. See Tabs sync fail
6. Note that your Bookrmarks Toolbar are now missing bookmarks which you had open in tabs

### Expected behavior
I would expect that failure or success to sync of one `New account` does not affect other accounts. Especially, syncing `Tabs` should never alter state of "real" bookmarks!

### Desktop
(please complete the following information)
 - OS: Debian Buster GNU/Linux
 - Browser:Firefox
 - Browser Version:78.10.0esr (64-bit)
 - Floccus version: 4.6.4
 - Floccus sync method: Nextcloud bookmarks

### Server
(please complete the following information)
 - OS: Debian Buster GNU/Linux
 - Nextcloud version:  20.0.9
 - Bookmarks app version: 4.1.0

### Debug log
It is often useful to provide a debug log file along with the issue. You can obtain a debug log of the most recent sync runs by clicking 'Debug log' in the bottom right corner of the floccus panel in your browser.

Note: As your debug log usually contains large parts of your bookmark data, instead of attaching it publicly to the issue here, I recommend uploading it privately at the following URL https://cloud.marcelklehr.de/s/PCi3iLWrzdMZSmw

- [x] Debug log provided

### Additional context
There is only this firefox syncing to that Nextcloud account, nothing other changes the bookmarks on Nextcloud instance (neither another floccus, nor manually via web interface - eg. it is used basically only as a backup for the time being).

**Comment by marcelklehr** [comment] 2021-07-14 18:57
Thank you for the detailed bug report! I'll try to fix this with the next release :)

**Comment by marcelklehr** [comment] 2021-07-15 16:21
> What happens is when Tabs are trying to sync (and fail due to #883) it also removes bookmarks with same URL from my Bookmarks Toolbar (and possibly Bookmarks Menu, have to do detailed comparison with backup).

Do you mean bookmarks with the same URL as your tabs are removed, or two bookmarks with the same URL are removed. Floccus currently deduplicates bookmarks in the same folder so removing one bookmark if the same URL is present in the same folder is by design (even if not expected, I'm working on that).

> Final effect is that any tabs I have open (or maybe only those I have open in multiple tabs?) are silently removed from all my bookmarks, which is bad.

I cannot reproduce either of these with Firefox 89.0.2 and it does sound rather odd. Tab syncing cannot access your local bookmarks And any syncing cannot delete bookmarks in other server folders (I wrote a test for this, which does not fail: https://github.com/floccusaddon/floccus/pull/914).

It may be the case that some bookmarks were removed due to faulty syncing when you were moving them around, there is an edge case that can happen in rare situations, which I still need to investigate.

**Comment by mnalis** [comment] 2021-07-16 03:27
> > What happens is when Tabs are trying to sync (and fail due to #883) it also removes bookmarks with same URL from my Bookmarks Toolbar (and possibly Bookmarks Menu, have to do detailed comparison with backup).
> 
> Do you mean bookmarks with the same URL as your tabs are removed, or two bookmarks with the same URL are removed. 

Bookmarks with the same URL as my tabs were removed. 

> Floccus currently deduplicates bookmarks in the same folder so removing one bookmark if the same URL is present in the same folder is by design (even if not expected, I'm working on that).

Yes, I've seen reported issues on that, but I don't think it is a case with me. When I disable tabs syncing, and leave other two "real bookmarks" accounts (`/Bookmarks Menu/` and `/Bookmarks Toolbar/`) enabled, the bookmarks are not removed any more (which I assume they would be if the there were duplicatas in "real bookmarks"). 

It did happen several times with same two bookmarks which I then re-added to bookmarks toolbar manually, and it kept removing them until I disabled `tabs sync`, after which they stayed in place. 

> > Final effect is that any tabs I have open (or maybe only those I have open in multiple tabs?) are silently removed from all my bookmarks, which is bad.
> 
> I cannot reproduce either of these with Firefox 89.0.2 and it does sound rather odd. Tab syncing cannot access your local bookmarks And any syncing cannot delete bookmarks in other server folders (I wrote a test for this, which does not fail: #914).
> 
> It may be the case that some bookmarks were removed due to faulty syncing when you were moving them around, there is an edge case that can happen in rare situations, which I still need to investigate.

I personally was not moving existing bookmarks around. I did add few new bookmarks (and re-added the ones that were removed), but I didn't moving bookmarks around (nor deleting) as far as I can remember. I did rearrange tabs and open new ones and close others, though, but as you say, it is strange that tabs should affect real bookmarks, but it happened.

**Comment by mnalis** [comment] 2021-07-16 12:25
Just to confirm, I tried it again. So:
- while I had all 3 accounts (`Sync tabs` included) active, it removed at least 1 bookmarks from `Bookmarks toolbar` (most easily visible, but I highly suspect at least one more was lost, at maybe more. I'll have to deeper forensics with my older bookmarks backups to verify what got lost, and restore it manually)
- I've re-added bookmark that was removed to `Bookmarks toolbar`
- for few days (I didn't manage to report bug immediately) I had only 2 real bookmarks account enabled (eg. `Sync tabs` **disabled**), started and stopped firefox several times, and the **bookmarks remained stable normally**
- In the meantime firefox got upgraded to `78.11.0esr (64-bit)`, nextcloud to `20.0.11` and bookmarks app to `4.2.2`
- then 9 hours ago  (when I wrote previous comment):
     - I've opened problematic bookmarks in 2 tabs 
     - I've click on `Sync now` on `Tabs` account. It removed only duplicate tab (which is not actually wanted, but a known "feature", so I don't worry about it), and thrown error from https://github.com/floccusaddon/floccus/issues/883
     - I've reopened the bookmarks so it is again in 2 tabs
     - I've re-enabled `Sync tabs` (so all 3 accounts are active again). Again, It only removed only duplicate tab, and thrown error from https://github.com/floccusaddon/floccus/issues/883
     - the bookmarks was still at it's place
     - I've shut down firefox and went to sleep

- **now** (9 hours later) I've turned on computer and firefox, and half an hour later remembered to look at `Bookmarks toolbar` and **now that bookmark is again gone**. So problem is still there and I can reproduce it. I've now disable sync tabs again, and clicked `cancel sync` (which is still not cancelled and says ` Synchronization in progress.` a good two minutes after I pressed it, while I expected it to do within a second or two, but that is cosmetic for some other ticket perhaps - I do have a ton of tabs open)

I'll try to anonymize logs somewhat and update this issue. Let me know if there is something more you want me to try out.

**Comment by mnalis** [comment] 2021-07-16 13:42
I've sent anonymized log `floccus-4.6.4-2021-07-16-anonymized.log` to the clould link provided. I've anonymized it with:
```
perl -pe 's{(://[^)]+?)\)}{$a=$1;$a=~s/\w/X/gu;$a}ge; s{(\[[^]]+?\])}{$a=$1;$a=~s/\w/D/gu;$a}ge' < floccus-4.6.4-2021-07-16.log > floccus-4.6.4-2021-07-16-anonymized.log
```
It is not perfect, but best I could do in reasonable amount of time.

What it should do is replace characters in bookmarks names with `D` and characters in URLs with `X`. I'm aware that is far from perfect, but due to GDPR concerns I can't really send all that data even privately to one trusted person. I hope it can still be somewhat helpful.

The URL that disappears from `Bookmarks toolbar` is `https://XXX.XX.XXX.XXX:XXXXX/`, indicated by `#19880` and `#723` in the logs.

 Let me know if you want me to look for something in the unanonymized logs, or if you want me to try something else. I'll try to delay further upgrades until we can find out what is causing this problematic behaviour (I'd be nervous if unrelated upgrade fixed things, because I'd then never know if it was really fixed, or if it is going to happen again when I forget about it and lower my guard). And above all, thanks for all your time and effort and work on this extension @marcelklehr !

**Comment by marcelklehr** [comment] 2021-07-16 15:36
Thank you for the log! It doesn't appear that anything was deleted from your server during the tab sync (there are some REMOVE actions in the diff, but the merge strategy ignores those and since the sync crashes during the CREATE stage already they wouldn't have been executed anyway). Could you provide logs for the sync run of the bookmarks account(s) after which the bookmarks were gone?

**Comment by marcelklehr** [comment] 2021-07-16 17:57
What is weird is that multiple created tabs with clearly different URLs seem to get the same ID `#723` from firefox.

**Comment by mnalis** [comment] 2021-07-16 18:54
(I'm still working on providing more debug data you asked for).

Yes, I can confirm all 7 URLs with same ID `#723` are indeed different. I have no idea where that ID comes from or why it is same, though - I do not really know anything about firefox internals. It does indeed sound problematic, if floccus is depending on that ID to be unique.

**Comment by mnalis** [comment] 2021-07-16 23:47
Ok, I've managed to reproduce it with verbose timeline from start to end. Probably too verbose, but hopefully it will also include interesting information.

(2021-07-16, times are TZ=CEST):
- 19:07 I've re-added bookmark, restarted firefox, and verified bookmark is still there. One copy of bookmark is open as tab.
- 19:09 I've enabled `sync tabs` in floccus
- 19:10 display says `tabs:  Synchronization in progress. `, `bookmarks toolbar:  Last synchronized: 1 hour ago `, `bookmarks menu:  Last synchronized: 10 minutes ago`
- 19:12 `sync tabs` has failed and restarted, bookmark is still there.
- 19:17 bookmark is still there, I open it in one more tab.
- 19:23 bookmark is still there. `sync tabs` fails and restarts all the time by itself...
- 19:25 I've noticed that some time before duplicate tab has disappeared, but bookmarks is still there (so 1 bookmark + 1 tab are active)
- 19:27 display says `tabs:  Synchronization in progress. `, `bookmarks toolbar:  Last synchronized: 2 hours ago `, `bookmarks menu:  Last synchronized: 28 minutes ago`
- 19:28 bookmark is still here. I click `Sync now` on `Bookmarks toolbar`
- 19:29 display says `tabs:  Synchronization in progress. `, `bookmarks toolbar:  Last synchronized: 32 seconds ago `, `bookmarks menu:  Last synchronized: 30 minutes ago`
        bookmark is still here
- 19:31 I save debug logs
- 19:33 I login to my nextcloud instance web interface (which I don't usually do) and notice that this bookmark is missing from that Bookmarks toolbar subfolder (there are 12 instead of 13 entries in that subfolder)
- 19:35 bookmark is still there, I open it in one more tab. few seconds later, duplicate tab disappears, but is still in bookmarks.
- 19:36 I save debug logs
- 19:37 display says `tabs:  Synchronization in progress. `, `bookmarks toolbar:  Last synchronized: 9 minutes ago `, `bookmarks menu:  Last synchronized: 38 minutes ago`
        bookmark is still here in firefox.
- 19:39 I backup bookmarks. Bookmarks is still there in firefox. I close firefox.
- 20:40 start firefox
        display says `tabs:   E027: Sync process was interrupted. `, `bookmarks toolbar:  Last synchronized: 1 hour ago `, `bookmarks menu:  Last synchronized: 17 minutes ago`
- 20:41 bookmark is still in firefox
- 20:46 bookmark is still in firefox
- 20:55 open second copy of the tab, backup bookmarks
- 20:57 duplicate tab is gone, bookmark is still here
- 22:45 bookmark is still in firefox, backup bookmarks
- 23:23 bookmark is still in firefox, closing firefox

(2021-07-17, times are TZ=CEST)
- 00:18 start firefox
- 00:24 I notice **bookmark is gone from toolbar**!
- 00:25 display says `tabs:  Synchronization in progress. `, `bookmarks toolbar:  Last synchronized: 6 minutes ago `, `bookmarks menu:  Last synchronized: 6 minutes ago`
- 00:26 I save debug logs (this is `floccus-4.6.4-2021-07-17_0026_anon.log`)
- 00:27 I backup boomarks and stop syncing tabs
- 01:33 I re-add the bookmark

attached in the cloud are `floccus-4.6.4-2021-07-16_2042_anon.log` (last log before closing firefox) and `floccus-4.6.4-2021-07-17_0026_anon.log` (really last log - when bookmark is gone). Problematic URL is the same as before `https://XXX.XX.XXX.XXX:XXXXX/`. I've noted in timeline above when I made bookmarks backups, so let me know if some value from some of them (`dateAdded` / `lastModified` / `guid` / `id` etc.) is useful for further debug.

**Comment by marcelklehr** [comment] 2021-07-17 11:05
Thank you for the detailed write up!

I've finally been able to reproduce this and it's indeed a bug in the create method of the nextcloud adapter. If there's already a bookmark with the same URL in a branch of the server tree ourside of the current server prefix, that will be moved to the location of the newly bookmark, instead of copying it.

**Comment by marcelklehr** [comment] 2021-07-17 11:27
#917 has the fix for this. The only issue left now, is that tabs have empty titles and override the title of an existing bookmark with the empty title. I'll try to come up with a solution for that.

**Closed** 2021-07-18 07:59 UTC
Labels: bug
