### ISSUE TITLE
Brave browser support?

### ISSUE THREAD

**Issue by susinths** [floccusaddon/floccus#984] opened 2021-10-12 20:57 UTC
### Describe the bug
I get E018: Couldn't authenticate with the server when i try to sync from the Brave browser

### To Reproduce
Set up Floccus like you'd do for Chrome using Nextcloud as the server and force a manual sync

### Expected behavior
No authentication issues
### Desktop
(please complete the following information)
 - OS: Fedora 34
 - Browser: Brave
 - Browser Version 1.26.77 Chromium: 91.0.4472.164 (Official Build) (64-bit)
 - Floccus version: 4.8.2
 - Floccus sync method: nextcloud folders

### Server
(please complete the following information)
 - OS: centos 8 stream
 - Nextcloud version: 21.0.5
 - Bookmarks app version: 10.0.0

**Comment by marcelklehr** [comment] 2021-10-21 19:47
This seems to be a duplicate of https://github.com/floccusaddon/floccus/issues/987
Feel free to reply to my questions for troublishing there :)

**Closed by marcelklehr** 2021-10-21 19:47 UTC
Labels: bug
