### ISSUE TITLE
Cannot login with google on desktop browser

### ISSUE THREAD

**Issue by Jank8** [floccusaddon/floccus#1533] opened 2024-01-29 13:47 UTC
### Which version of floccus are you using?

5.0.9

### Sync method

Google Drive

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Brave 1.62.153 Chromium: 121.0.6167.85

### Describe the Bug

Cannot login with google, everytime "something went wrong".
![image](https://github.com/floccusaddon/floccus/assets/99371372/2b54bf45-d273-4334-9b14-d4293cb1dfbb)

### Expected Behavior

Login just like i logged in on android.

### To Reproduce

Try to login on Brave, doenst work also on my chrome and other network connections.

### Debug log provided

- [ ] I have provided a debug log file

**Comment by marcelklehr** [comment] 2024-02-03 17:21
Duplicate of https://github.com/floccusaddon/floccus/issues/1529

**Closed by marcelklehr** 2024-02-03 17:21 UTC
Labels: bug
