### ISSUE TITLE
"Cannot read property 'filter' of undefined"

### ISSUE THREAD

**Issue by ab-cc** [floccusaddon/floccus#868] opened 2021-04-17 11:35 UTC
### Describe the bug
When using Google Drive and using file paths, sync results in the mentioned error. Sync works only without a path as shown in the second screenshot.

### Expected behavior
Ability to use file paths...

### Screenshots
![image](https://user-images.githubusercontent.com/45005187/115111570-90ec8180-9f9e-11eb-9272-d319a76e4a14.png)
![image](https://user-images.githubusercontent.com/45005187/115111676-08baac00-9f9f-11eb-9c02-dbb835612355.png)

**Comment by marcelklehr** [comment] 2021-04-21 14:36
Thank you for your feedback!

Specifying a path is currently not supported, I'll correct the label for the input field.

As such, this is a duplicate of #867

**Closed by marcelklehr** 2021-04-21 14:36 UTC
Labels: bug
