### ISSUE TITLE
Google Drive account won't link 

### ISSUE THREAD

**Issue by turkeyphant** [floccusaddon/floccus#1529] opened 2024-01-23 15:01 UTC
### Which version of floccus are you using?

5.0.9

### Sync method

Google Drive

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Version 120.0.6099.217 (Official Build) (64-bit)

### Describe the Bug

Can't connect Google account to sync to Drive

### Expected Behavior

Connect to Google Account so extension works

### To Reproduce

Fresh install of Floccus,.
+ New Profile
How do you want to Sync
Google Drive
Continue
Log in with Google
Choose an Account
floccus bookmark sync wants access to your Google Account
Continue
![image](https://github.com/floccusaddon/floccus/assets/8129583/0290362a-aa41-4a33-8117-7acaaaa6638c)

### Debug log provided

- [ ] I have provided a debug log file

**Comment by beningodfrey4** [comment] 2024-01-25 10:51
+1 facing the same issue

**Comment by marcelklehr** [comment] 2024-01-25 13:40
> Version 120.0.6099.217 (Official Build) (64-bit)

I assume this is Chrome?

**Comment by marcelklehr** [comment] 2024-01-27 11:14
I cannot reproduce this.

**Comment by beningodfrey4** [comment] 2024-01-27 14:46
Yeah... I tried in a fresh profile and it worked.

 So proceeded to try after disabling ad and cookie related extensions and it worked.

@turkeyphant maybe give it a shot and close this if so. Apologies.

**Closed** 2024-03-08 19:34 UTC
Labels: bug, waiting for more information
