### ISSUE TITLE
Sync interval

### ISSUE THREAD

**Issue by kalekad** [floccusaddon/floccus#1310] opened 2023-01-01 19:09 UTC
### Which version of floccus are you using?

v4.18.0

### Sync method

WebDAV

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Tor Browser 12.0.1(Firefox 102.6esr), Android

### Describe the Bug

I set the sync interval to 5 minutes and save. I reopen the settings and the sync interval is at 15 minutes. 

### Expected Behavior

A sync interval of 5 minutes remains stored.

### To Reproduce

-

### Debug log provided

- [ ] I have provided a debug log file

**Comment by marcelklehr** [comment] 2023-01-08 16:06
It seems only 5minutes was forbidden due to a legacy rule. Fixed now.

**Comment by marcelklehr** [comment] 2023-01-15 17:41
Confirmed. Weird. I tested this before the release and it was working :/

**Closed** 2023-01-15 17:43 UTC
Labels: bug

**Comment by kolinger** [comment] 2023-11-27 12:29
Last fixed removed one part of condition but identical condition was left few line bellow: https://github.com/floccusaddon/floccus/blob/8812859e7bed4e9000b117ce0a89d6b56ab5c4ab/src/ui/components/OptionSyncInterval.vue#L49-L61
Where zero index is taken as invalid value and overridden by default 15 minute interval. But zero index is first option of interval and that's 5 minutes, thus 5 minutes is always overridden by 15 minutes.

This is why 5 minute interval still can't be saved with 4.19.1 as #1414 reports and thus this issues wasn't fixed yet.

**Comment by marcelklehr** [comment] 2023-12-06 19:08
Thank you @kolinger for investigating this!
