### ISSUE TITLE
Bookmark file not create on WebDAV server

### ISSUE THREAD

**Issue by truegreyhound** [floccusaddon/floccus#824] opened 2021-02-07 20:23 UTC
### Describe the bug
After a few tests with Floccus and LoFloccus, I decided to test Floccus in conjunction with a WebDAV server.
Floccus reports a successful synchronization after an E109 error, but no xbel file is generated.
After the synchronization, all entries in the bookmarks bar are deleted, the entries in the bookmarks menu were not synchronized according to the log

### To Reproduce
1. Setup a fresh WebDAV server, check with other client he is working
2. Configure Floccus for syncing root folder and new initial sync
![grafik](https://user-images.githubusercontent.com/24899637/107158047-ce71d480-6987-11eb-972c-d698ca98741c.png)
3. click on synchronize now
4. After synchronization
![grafik](https://user-images.githubusercontent.com/24899637/107158091-142e9d00-6988-11eb-90fe-fd0a4996ad79.png)

### Expected behavior
a xbel file on the WebDAV server, but nothing
![grafik](https://user-images.githubusercontent.com/24899637/107158112-31fc0200-6988-11eb-8fda-6a77cf9ee5de.png)

Then I copied an xbel file from the LoFloccus test to the WebDAV server and synchronized it again. This file has then been changed. It seems like a new file cannot be created. In the screenshot this can be seen as bookmarks-all.xbel-test1.

As I understand it, clicking on "new synchronization" clears the cache and the complete list of bookmarks should be in the xbel file. However, the "remove" indicates that the cache was not empty. How can I control the clearing of the cache?

### Desktop
(please complete the following information)
 - OS: Windows 10 20H2 german
 - Browser FireFox
 - Browser Version 85
 - Floccus version: 4.4.10
 - Floccus sync method: webdav

### Server
debian buster, with Apache 2.4

### Debug log
from FireFox
```20:28:21.604 2021-02-07T19:28:21.604Z Starting sync process for account floccus@192.168.200.107 background-script.js:1:9771
20:28:21.905 2021-02-07T19:28:21.906Z onSyncStart: begin background-script.js:1:9771
20:28:21.906 2021-02-07T19:28:21.907Z http://192.168.200.107:83/floccus/bookmarks-all.xbel.lock background-script.js:1:9771
20:28:21.928 2021-02-07T19:28:21.929Z http://192.168.200.107:83/floccus/bookmarks-all.xbel.lock background-script.js:1:9771
20:28:21.977 2021-02-07T19:28:21.978Z onSyncStart: completed background-script.js:1:9771
20:28:21.981 2021-02-07T19:28:21.982Z Using "merge default" strategy (no cache available) background-script.js:1:9771
20:28:22.548 2021-02-07T19:28:22.549Z Overriding title of built-in node menu________ Lesezeichen-Menü => Bookmarks Menu background-script.js:1:9771
20:28:22.581 2021-02-07T19:28:22.581Z Overriding title of built-in node toolbar_____ Lesezeichen-Symbolleiste => Bookmarks Bar background-script.js:1:9771
20:28:22.581 2021-02-07T19:28:22.582Z Overriding title of built-in node unfiled_____ Weitere Lesezeichen => Other Bookmarks background-script.js:1:9771
20:28:22.625 2021-02-07T19:28:22.625Z Filtered out the following duplicates before syncing 
Array [ {…} ]
background-script.js:1:9771
20:28:22.626 2021-02-07T19:28:22.627Z (local)REMOVE 
Object { type: "bookmark", id: "dUsfz9AHi7sP", parentId: "7HZDaip0RT-b", title: "Linux - Wegweiser zur Installation & Konfiguration", tags: undefined, location: "Local", url: "http://www.oreilly.de/german/freebooks/rlinux3ger/linux_wegIVZ.html" }
background-script.js:1:9771
20:28:22.630 2021-02-07T19:28:22.630Z Filtered out the following duplicates before syncing 
Array [ {…} ]
background-script.js:1:9771
20:28:22.630 2021-02-07T19:28:22.630Z (local)REMOVE 
Object { type: "bookmark", id: "UZb_sMaiQ1nq", parentId: "Jy-is7dzwxSt", title: "Ghost@dmin!, Ghostadmin, Die ultimative Site ums Netzwerk & mehr! Netzwerk, Network, NIC, Netzwerkkarte, Netzwerkadapter, Secur", tags: undefined, location: "Local", url: "http://themen01.exit.de/linux/member/ghostadmin/" }
background-script.js:1:9771
20:28:22.632 2021-02-07T19:28:22.632Z Filtered out the following duplicates before syncing 
Array(6) [ {…}, {…}, {…}, {…}, {…}, {…} ]
background-script.js:1:9771
. . . 
20:28:22.653 2021-02-07T19:28:22.654Z 
Object { localDiff: {…}, serverDiff: {…} }
background-script.js:1:9771
20:28:22.730 2021-02-07T19:28:22.730Z 
Object { localPlan: {…}, serverPlan: {…} }
background-script.js:1:9771
20:28:22.770 2021-02-07T19:28:22.770Z 
Object { localTreeRoot: {…}, serverTreeRoot: {…}, cacheTreeRoot: {…} }
background-script.js:1:9771
20:28:23.317 2021-02-07T19:28:23.317Z CREATEFOLDER 
Object { folder: {…} }
background-script.js:1:9771
20:28:23.323 2021-02-07T19:28:23.324Z CREATEFOLDER 
Object { folder: {…} }
background-script.js:1:9771
20:28:23.324 2021-02-07T19:28:23.324Z CREATEFOLDER 
Object { folder: {…} }
background-script.js:1:9771
20:28:23.324 2021-02-07T19:28:23.324Z CREATEFOLDER 
Object { folder: {…} }
background-script.js:1:9771
20:28:23.325 2021-02-07T19:28:23.325Z BULKIMPORT 
Object { id: 1, folder: {…} }
background-script.js:1:9771
20:28:25.557 2021-02-07T19:28:25.558Z 
Object { reorderings: {…} }
background-script.js:1:9771
20:28:25.557 2021-02-07T19:28:25.558Z 
Object { reorderings: {…} }
background-script.js:1:9771
20:28:26.243 2021-02-07T19:28:26.243Z Overriding title of built-in node menu________ Lesezeichen-Menü => Bookmarks Menu background-script.js:1:9771
20:28:26.266 2021-02-07T19:28:26.266Z Overriding title of built-in node toolbar_____ Lesezeichen-Symbolleiste => Bookmarks Bar background-script.js:1:9771
20:28:26.266 2021-02-07T19:28:26.266Z Overriding title of built-in node unfiled_____ Weitere Lesezeichen => Other Bookmarks background-script.js:1:9771
20:28:26.319 2021-02-07T19:28:26.320Z onSyncComplete background-script.js:1:9771
20:28:26.695 Error: E019: HTTP Status 404. Anfrage vom Typ PUT  fehlgeschlagen. Überprüfen Sie die Server-Konfiguration und das Server-Log
    uploadFile moz-extension://69ec8960-d7e2-45fd-a230-47a7a3ffadad/dist/js/background-script.js:1
background-script.js:1:19148
20:28:26.695
Syncing failed with E019: HTTP Status 404. Anfrage vom Typ PUT  fehlgeschlagen. Überprüfen Sie die Server-Konfiguration und das Server-Log background-script.js:1:19191
    sync moz-extension://69ec8960-d7e2-45fd-a230-47a7a3ffadad/dist/js/background-script.js:1
20:28:26.695 2021-02-07T19:28:26.696Z Syncing failed with E019: HTTP Status 404. Anfrage vom Typ PUT  fehlgeschlagen. Überprüfen Sie die Server-Konfiguration und das Server-Log background-script.js:1:9771
20:28:26.699 2021-02-07T19:28:26.699Z onSyncFail background-script.js:1:9771
20:28:51.954 2021-02-07T19:28:51.954Z Starting sync process for account floccus@192.168.200.107 background-script.js:1:9771
20:28:52.196 2021-02-07T19:28:52.196Z onSyncStart: begin background-script.js:1:9771
20:28:52.197 2021-02-07T19:28:52.198Z http://192.168.200.107:83/floccus/bookmarks-all.xbel.lock background-script.js:1:9771
20:28:52.209 2021-02-07T19:28:52.209Z http://192.168.200.107:83/floccus/bookmarks-all.xbel.lock background-script.js:1:9771
20:28:52.237 2021-02-07T19:28:52.237Z onSyncStart: completed background-script.js:1:9771
20:28:52.267 2021-02-07T19:28:52.268Z Using "default" strategy background-script.js:1:9771
20:28:52.709 2021-02-07T19:28:52.710Z Overriding title of built-in node menu________ Lesezeichen-Menü => Bookmarks Menu background-script.js:1:9771
20:28:52.734 2021-02-07T19:28:52.735Z Overriding title of built-in node toolbar_____ Lesezeichen-Symbolleiste => Bookmarks Bar background-script.js:1:9771
20:28:52.735 2021-02-07T19:28:52.735Z Overriding title of built-in node unfiled_____ Weitere Lesezeichen => Other Bookmarks background-script.js:1:9771
20:28:53.651 2021-02-07T19:28:53.651Z 
Object { localDiff: {…}, serverDiff: {…} }
background-script.js:1:9771
20:28:53.665 2021-02-07T19:28:53.666Z 
Object { localPlan: {…}, serverPlan: {…} }
background-script.js:1:9771
20:28:53.678 2021-02-07T19:28:53.679Z 
Object { localTreeRoot: {…}, serverTreeRoot: {…}, cacheTreeRoot: {…} }
background-script.js:1:9771
20:28:54.127 2021-02-07T19:28:54.127Z 
Object { reorderings: {…} }
background-script.js:1:9771
20:28:54.127 2021-02-07T19:28:54.128Z 
Object { reorderings: {…} }
background-script.js:1:9771
20:28:54.531 2021-02-07T19:28:54.531Z Overriding title of built-in node menu________ Lesezeichen-Menü => Bookmarks Menu background-script.js:1:9771
20:28:54.551 2021-02-07T19:28:54.552Z Overriding title of built-in node toolbar_____ Lesezeichen-Symbolleiste => Bookmarks Bar background-script.js:1:9771
20:28:54.551 2021-02-07T19:28:54.552Z Overriding title of built-in node unfiled_____ Weitere Lesezeichen => Other Bookmarks background-script.js:1:9771
20:28:54.623 2021-02-07T19:28:54.624Z onSyncComplete background-script.js:1:9771
20:28:54.838 2021-02-07T19:28:54.839Z No changes to the server version necessary background-script.js:1:9771
20:28:54.853 2021-02-07T19:28:54.853Z Successfully ended sync process for account floccus@192.168.200.107 background-script.js:1:9771
```

from WebDAV server
```
[Sun Feb 07 19:27:25.270981 2021] [authz_core:debug] [pid 20224:tid 140495988696832] mod_authz_core.c(820): [client 192.168.200.210:16809] AH01626: authorization result of Require valid-user : denied (no authenticated user yet)
[Sun Feb 07 19:27:25.271084 2021] [authz_core:debug] [pid 20224:tid 140495988696832] mod_authz_core.c(820): [client 192.168.200.210:16809] AH01626: authorization result of <RequireAny>: denied (no authenticated user yet)
[Sun Feb 07 19:28:22.557572 2021] [authz_core:debug] [pid 20224:tid 140495997089536] mod_authz_core.c(820): [client 192.168.200.210:16854] AH01626: authorization result of Require valid-user : denied (no authenticated user yet)
[Sun Feb 07 19:28:22.557640 2021] [authz_core:debug] [pid 20224:tid 140495997089536] mod_authz_core.c(820): [client 192.168.200.210:16854] AH01626: authorization result of <RequireAny>: denied (no authenticated user yet)
[Sun Feb 07 19:28:22.561058 2021] [authz_core:debug] [pid 20224:tid 140495997089536] mod_authz_core.c(820): [client 192.168.200.210:16854] AH01626: authorization result of Require valid-user : granted
[Sun Feb 07 19:28:22.561097 2021] [authz_core:debug] [pid 20224:tid 140495997089536] mod_authz_core.c(820): [client 192.168.200.210:16854] AH01626: authorization result of <RequireAny>: granted
[Sun Feb 07 19:28:22.561343 2021] [core:info] [pid 20224:tid 140495997089536] [client 192.168.200.210:16854] AH00128: File does not exist: /var/www/webdav/floccus/bookmarks-all.xbel.lock
[Sun Feb 07 19:28:22.575340 2021] [authz_core:debug] [pid 20224:tid 140496005482240] mod_authz_core.c(820): [client 192.168.200.210:16854] AH01626: authorization result of Require valid-user : denied (no authenticated user yet)
[Sun Feb 07 19:28:22.575395 2021] [authz_core:debug] [pid 20224:tid 140496005482240] mod_authz_core.c(820): [client 192.168.200.210:16854] AH01626: authorization result of <RequireAny>: denied (no authenticated user yet)
[Sun Feb 07 19:28:22.576517 2021] [authz_core:debug] [pid 20224:tid 140496005482240] mod_authz_core.c(820): [client 192.168.200.210:16854] AH01626: authorization result of Require valid-user : granted
[Sun Feb 07 19:28:22.576540 2021] [authz_core:debug] [pid 20224:tid 140496005482240] mod_authz_core.c(820): [client 192.168.200.210:16854] AH01626: authorization result of <RequireAny>: granted
[Sun Feb 07 19:28:22.598838 2021] [authz_core:debug] [pid 20224:tid 140496030660352] mod_authz_core.c(820): [client 192.168.200.210:16854] AH01626: authorization result of Require valid-user : denied (no authenticated user yet)
[Sun Feb 07 19:28:22.598877 2021] [authz_core:debug] [pid 20224:tid 140496030660352] mod_authz_core.c(820): [client 192.168.200.210:16854] AH01626: authorization result of <RequireAny>: denied (no authenticated user yet)
[Sun Feb 07 19:28:22.599857 2021] [authz_core:debug] [pid 20224:tid 140496030660352] mod_authz_core.c(820): [client 192.168.200.210:16854] AH01626: authorization result of Require valid-user : granted
[Sun Feb 07 19:28:22.599873 2021] [authz_core:debug] [pid 20224:tid 140496030660352] mod_authz_core.c(820): [client 192.168.200.210:16854] AH01626: authorization result of <RequireAny>: granted
[Sun Feb 07 19:28:22.599999 2021] [authz_core:debug] [pid 20224:tid 140496030660352] mod_authz_core.c(820): [client 192.168.200.210:16854] AH01626: authorization result of Require valid-user : denied (no authenticated user yet)
[Sun Feb 07 19:28:22.600016 2021] [authz_core:debug] [pid 20224:tid 140496030660352] mod_authz_core.c(820): [client 192.168.200.210:16854] AH01626: authorization result of <RequireAny>: denied (no authenticated user yet)
[Sun Feb 07 19:28:22.600962 2021] [authz_core:debug] [pid 20224:tid 140496030660352] mod_authz_core.c(820): [client 192.168.200.210:16854] AH01626: authorization result of Require valid-user : granted
[Sun Feb 07 19:28:22.600975 2021] [authz_core:debug] [pid 20224:tid 140496030660352] mod_authz_core.c(820): [client 192.168.200.210:16854] AH01626: authorization result of <RequireAny>: granted
[Sun Feb 07 19:28:22.601006 2021] [negotiation:error] [pid 20224:tid 140496030660352] [client 192.168.200.210:16854] AH00687: Negotiation: discovered file(s) matching request: /var/www/webdav/floccus/bookmarks-all.xbel (None could be negotiated).
[Sun Feb 07 19:28:27.325247 2021] [authz_core:debug] [pid 20224:tid 140495711868672] mod_authz_core.c(820): [client 192.168.200.210:16854] AH01626: authorization result of Require valid-user : denied (no authenticated user yet)
[Sun Feb 07 19:28:27.325308 2021] [authz_core:debug] [pid 20224:tid 140495711868672] mod_authz_core.c(820): [client 192.168.200.210:16854] AH01626: authorization result of <RequireAny>: denied (no authenticated user yet)
[Sun Feb 07 19:28:27.326620 2021] [authz_core:debug] [pid 20224:tid 140495711868672] mod_authz_core.c(820): [client 192.168.200.210:16854] AH01626: authorization result of Require valid-user : granted
[Sun Feb 07 19:28:27.326641 2021] [authz_core:debug] [pid 20224:tid 140495711868672] mod_authz_core.c(820): [client 192.168.200.210:16854] AH01626: authorization result of <RequireAny>: granted
[Sun Feb 07 19:28:27.326763 2021] [authz_core:debug] [pid 20224:tid 140495711868672] mod_authz_core.c(820): [client 192.168.200.210:16854] AH01626: authorization result of Require valid-user : denied (no authenticated user yet)
[Sun Feb 07 19:28:27.326778 2021] [authz_core:debug] [pid 20224:tid 140495711868672] mod_authz_core.c(820): [client 192.168.200.210:16854] AH01626: authorization result of <RequireAny>: denied (no authenticated user yet)
[Sun Feb 07 19:28:27.327832 2021] [authz_core:debug] [pid 20224:tid 140495711868672] mod_authz_core.c(820): [client 192.168.200.210:16854] AH01626: authorization result of Require valid-user : granted
[Sun Feb 07 19:28:27.327845 2021] [authz_core:debug] [pid 20224:tid 140495711868672] mod_authz_core.c(820): [client 192.168.200.210:16854] AH01626: authorization result of <RequireAny>: granted
[Sun Feb 07 19:28:27.327878 2021] [negotiation:error] [pid 20224:tid 140495711868672] [client 192.168.200.210:16854] AH00687: Negotiation: discovered file(s) matching request: /var/www/webdav/floccus/bookmarks-all.xbel (None could be negotiated).
[Sun Feb 07 19:28:27.341684 2021] [authz_core:debug] [pid 20224:tid 140495619614464] mod_authz_core.c(820): [client 192.168.200.210:16854] AH01626: authorization result of Require valid-user : denied (no authenticated user yet)
[Sun Feb 07 19:28:27.341734 2021] [authz_core:debug] [pid 20224:tid 140495619614464] mod_authz_core.c(820): [client 192.168.200.210:16854] AH01626: authorization result of <RequireAny>: denied (no authenticated user yet)
[Sun Feb 07 19:28:27.342698 2021] [authz_core:debug] [pid 20224:tid 140495619614464] mod_authz_core.c(820): [client 192.168.200.210:16854] AH01626: authorization result of Require valid-user : granted
[Sun Feb 07 19:28:27.342713 2021] [authz_core:debug] [pid 20224:tid 140495619614464] mod_authz_core.c(820): [client 192.168.200.210:16854] AH01626: authorization result of <RequireAny>: granted
[Sun Feb 07 19:28:52.843513 2021] [authz_core:debug] [pid 20224:tid 140495611221760] mod_authz_core.c(820): [client 192.168.200.210:16876] AH01626: authorization result of Require valid-user : denied (no authenticated user yet)
[Sun Feb 07 19:28:52.843576 2021] [authz_core:debug] [pid 20224:tid 140495611221760] mod_authz_core.c(820): [client 192.168.200.210:16876] AH01626: authorization result of <RequireAny>: denied (no authenticated user yet)
[Sun Feb 07 19:28:52.844699 2021] [authz_core:debug] [pid 20224:tid 140495611221760] mod_authz_core.c(820): [client 192.168.200.210:16876] AH01626: authorization result of Require valid-user : granted
[Sun Feb 07 19:28:52.844721 2021] [authz_core:debug] [pid 20224:tid 140495611221760] mod_authz_core.c(820): [client 192.168.200.210:16876] AH01626: authorization result of <RequireAny>: granted
[Sun Feb 07 19:28:52.844845 2021] [core:info] [pid 20224:tid 140495611221760] [client 192.168.200.210:16876] AH00128: File does not exist: /var/www/webdav/floccus/bookmarks-all.xbel.lock
[Sun Feb 07 19:28:52.850600 2021] [authz_core:debug] [pid 20224:tid 140495728654080] mod_authz_core.c(820): [client 192.168.200.210:16876] AH01626: authorization result of Require valid-user : denied (no authenticated user yet)
[Sun Feb 07 19:28:52.850672 2021] [authz_core:debug] [pid 20224:tid 140495728654080] mod_authz_core.c(820): [client 192.168.200.210:16876] AH01626: authorization result of <RequireAny>: denied (no authenticated user yet)
[Sun Feb 07 19:28:52.851753 2021] [authz_core:debug] [pid 20224:tid 140495728654080] mod_authz_core.c(820): [client 192.168.200.210:16876] AH01626: authorization result of Require valid-user : granted
[Sun Feb 07 19:28:52.851769 2021] [authz_core:debug] [pid 20224:tid 140495728654080] mod_authz_core.c(820): [client 192.168.200.210:16876] AH01626: authorization result of <RequireAny>: granted
[Sun Feb 07 19:28:52.857033 2021] [authz_core:debug] [pid 20224:tid 140495628007168] mod_authz_core.c(820): [client 192.168.200.210:16876] AH01626: authorization result of Require valid-user : denied (no authenticated user yet)
[Sun Feb 07 19:28:52.857076 2021] [authz_core:debug] [pid 20224:tid 140495628007168] mod_authz_core.c(820): [client 192.168.200.210:16876] AH01626: authorization result of <RequireAny>: denied (no authenticated user yet)
[Sun Feb 07 19:28:52.858156 2021] [authz_core:debug] [pid 20224:tid 140495628007168] mod_authz_core.c(820): [client 192.168.200.210:16876] AH01626: authorization result of Require valid-user : granted
[Sun Feb 07 19:28:52.858171 2021] [authz_core:debug] [pid 20224:tid 140495628007168] mod_authz_core.c(820): [client 192.168.200.210:16876] AH01626: authorization result of <RequireAny>: granted
[Sun Feb 07 19:28:52.858289 2021] [authz_core:debug] [pid 20224:tid 140495628007168] mod_authz_core.c(820): [client 192.168.200.210:16876] AH01626: authorization result of Require valid-user : denied (no authenticated user yet)
[Sun Feb 07 19:28:52.858305 2021] [authz_core:debug] [pid 20224:tid 140495628007168] mod_authz_core.c(820): [client 192.168.200.210:16876] AH01626: authorization result of <RequireAny>: denied (no authenticated user yet)
[Sun Feb 07 19:28:52.859359 2021] [authz_core:debug] [pid 20224:tid 140495628007168] mod_authz_core.c(820): [client 192.168.200.210:16876] AH01626: authorization result of Require valid-user : granted
[Sun Feb 07 19:28:52.859372 2021] [authz_core:debug] [pid 20224:tid 140495628007168] mod_authz_core.c(820): [client 192.168.200.210:16876] AH01626: authorization result of <RequireAny>: granted
[Sun Feb 07 19:28:52.859404 2021] [negotiation:error] [pid 20224:tid 140495628007168] [client 192.168.200.210:16876] AH00687: Negotiation: discovered file(s) matching request: /var/www/webdav/floccus/bookmarks-all.xbel (None could be negotiated).
[Sun Feb 07 19:28:55.481672 2021] [authz_core:debug] [pid 20224:tid 140495762224896] mod_authz_core.c(820): [client 192.168.200.210:16876] AH01626: authorization result of Require valid-user : denied (no authenticated user yet)
[Sun Feb 07 19:28:55.481738 2021] [authz_core:debug] [pid 20224:tid 140495762224896] mod_authz_core.c(820): [client 192.168.200.210:16876] AH01626: authorization result of <RequireAny>: denied (no authenticated user yet)
[Sun Feb 07 19:28:55.482856 2021] [authz_core:debug] [pid 20224:tid 140495762224896] mod_authz_core.c(820): [client 192.168.200.210:16876] AH01626: authorization result of Require valid-user : granted
[Sun Feb 07 19:28:55.482884 2021] [authz_core:debug] [pid 20224:tid 140495762224896] mod_authz_core.c(820): [client 192.168.200.210:16876] AH01626: authorization result of <RequireAny>: granted
```

**Comment by marcelklehr** [comment] 2021-02-07 21:01
That bot is a bit overzealous apparently...

**Comment by bhlevca** [comment] 2021-02-08 02:28
Marcel, I have the same issue. The Webdav solution does not work at all. It is basically stuck and does not advance at all for hours and even days. I think that there is a major design problem with the file lock which may work for 2 devices but not for more as it will be in a racing condition that only one lock cannot solve.
I tried to go back to the Bookmarks App, but since v 4.4.10  nothing works. My Bookmark app hosted on a Raspberry Pi 4 is useless as it is very slow and I have the latest nextcloud version as of today. 

I made a contribution as a sponsor to help with the development, but I need a functional app to store my bookmarks and I will stop using it for a while until things get better. The issue appears on all the browsers.  
I will use the private Brave sync which has synced all my 3000 bookmarks in less then 30 seconds.  There must be a way that floccus can be made more reliable and fast.  If money can help I will contribute more, but at this time floccus is at its worst that has ever been, at least for me and I tried to erase bookmarks , and do it form scratch but nothing helped.

**Comment by marcelklehr** [comment] 2021-02-08 11:13
Thanks for your feedback, folks! I'm sorry for your troubles. This has been due to a stale cache, indeed.

It seems this has been reported in #814 #819 and #650, but I couldn't reproduce it then. The hint with the sync from scratch was the clue.

@bhlevca Thank you for your donation! Initial sync with the bookmarks app is usually slower than normal, but subsequent syncs should be quite fast.

**Comment by truegreyhound** [comment] 2021-02-08 21:55
I did a new test today.
First a new initial synchronization without an existing xbel file. This ends with the following error:
```
. . .
2021-02-08T21:29:33.723Z { reorderings: [] }
2021-02-08T21:29:33.726Z { reorderings: [] }
2021-02-08T21:29:34.275Z Overriding title of built-in node menu________ Lesezeichen-Menü => Bookmarks Menu
2021-02-08T21:29:34.301Z Overriding title of built-in node toolbar_____ Lesezeichen-Symbolleiste => Bookmarks Bar
2021-02-08T21:29:34.303Z Overriding title of built-in node unfiled_____ Weitere Lesezeichen => Other Bookmarks
2021-02-08T21:29:34.390Z onSyncComplete
2021-02-08T21:29:34.993Z Syncing failed with E019: HTTP Status 404. Anfrage vom Typ PUT  fehlgeschlagen. Überprüfen Sie die Server-Konfiguration und das Server-Log
2021-02-08T21:29:34.998Z onSyncFail
```

Then I created an empty xbel file in the WebDAV directory via WinSCP:
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE xbel PUBLIC "+//IDN python.org//DTD XML Bookmark Exchange Language 1.0//EN//XML" "http://pyxml.sourceforge.net/topics/dtds/xbel.dtd">
<xbel version="1.0">
</xbel>
```
and then performed an initial synchronization again:
```
2021-02-08T21:44:51.351Z Starting sync process for account floccus@192.168.200.107
2021-02-08T21:44:51.598Z onSyncStart: begin
2021-02-08T21:44:51.601Z http://192.168.200.107:83/floccus/bookmarks-all.xbel.lock
2021-02-08T21:44:51.616Z http://192.168.200.107:83/floccus/bookmarks-all.xbel.lock
2021-02-08T21:44:51.674Z onSyncStart: completed
2021-02-08T21:44:51.677Z Using "merge default" strategy (no cache available)
2021-02-08T21:44:52.169Z Overriding title of built-in node menu________ Lesezeichen-Menü => Bookmarks Menu
2021-02-08T21:44:52.195Z Overriding title of built-in node toolbar_____ Lesezeichen-Symbolleiste => Bookmarks Bar
2021-02-08T21:44:52.196Z Overriding title of built-in node unfiled_____ Weitere Lesezeichen => Other Bookmarks
2021-02-08T21:44:52.272Z { localDiff: 
   [ { type: 'CREATE',
       payload: 
        + #menu________[Bookmarks Menu] parentId: root________, hash: undefined
        - #OxzxxhXct8Ha[Lesezeichen-Add-ons herunterladen](http://de.add-ons.mozilla.com/de/firefox/bookmarks/) parentId: menu________
        + #WBI6bs1HVtf1[Mozilla Firefox] parentId: menu________, hash: undefined
          - #d2THlkVVnORE[Firefox anpassen](http://de.www.mozilla.com/de/firefox/customize/) parentId: WBI6bs1HVtf1
          - #EYPLJk7w7rzx[Hilfe und Anleitungen](http://de.www.mozilla.com/de/firefox/help/) parentId: WBI6bs1HVtf1
          - #YaLultRgALqa[Machen Sie mit](http://de.www.mozilla.com/de/firefox/community/) parentId: WBI6bs1HVtf1
          - #tFyXupSTF6CD[Über uns](http://de.www.mozilla.com/de/firefox/about/) parentId: WBI6bs1HVtf1
        + #7HZDaip0RT-b[2Downloading] parentId: menu________, hash: undefined
          - #gs2pF3uNbN3_[Firewall Handbuch für LINUX 2.0 und 2.2](http://www.little-idiot.de/firewall/zusammen.html) parentId: 7HZDaip0RT-b
. . .
2021-02-08T21:44:55.631Z { reorderings: [] }
2021-02-08T21:44:55.633Z { reorderings: [] }
2021-02-08T21:44:56.408Z Overriding title of built-in node menu________ Lesezeichen-Menü => Bookmarks Menu
2021-02-08T21:44:56.448Z Overriding title of built-in node toolbar_____ Lesezeichen-Symbolleiste => Bookmarks Bar
2021-02-08T21:44:56.450Z Overriding title of built-in node unfiled_____ Weitere Lesezeichen => Other Bookmarks
2021-02-08T21:44:56.533Z onSyncComplete
2021-02-08T21:44:57.511Z Successfully ended sync process for account floccus@192.168.200.107
```
the xbel file has now been updated.

The problem is therefore that it does not appear to be checked whether an xbel file already exists and that it may have to be created again.

**Comment by marcelklehr** [comment] 2021-02-09 09:37
> E019: HTTP Status 404. Anfrage vom Typ PUT fehlgeschlagen.

@truegreyhound The webdav adapter is extensively unit-tested with Nextcloud where this request works as intended. I'm happy to change code in floccus to make this work, but as it stands it seems like this would be a problem with your server configuration, as PUT requests should create a new file if it doesn't exist.

**Comment by truegreyhound** [comment] 2021-02-09 20:33
I had successfully tested my WebDAV installation with various clients.
Today I extended the logging on the WebDAV server and found the following message: 
"Negotiation: discovered file (s) matching request: /var/www/webdav/floccus/bookmarks-all.xbel (None could be negotiated)"

After deactivating MultiViews, Floccus created the file successfully.
Here is my current configuration:
```
DavLockDB /var/www/webdav/DavLock.db
Listen 83
<VirtualHost *:83>
   ServerAdmin webmaster@localhost
   ServerName XXXXX

   LogLevel debug

   ErrorLog ${APACHE_LOG_DIR}/webdav-error.log
   CustomLog ${APACHE_LOG_DIR}/webdav-access.log combined

   DocumentRoot /var/www/webdav
   <Directory />
      Options FollowSymLinks
      AllowOverride None
   </Directory>

   # Repository location
   <Directory /var/www/webdav>
      DavDepthInfinity On
      #Options Indexes MultiViews
      Options Indexes
      AllowOverride None
      Require all granted
   </Directory>

   Alias /floccus /var/www/webdav/floccus

   <Location /floccus>
      DAV On
      <Limit GET POST PUT DELETE PROPFIND PROPPATCH MKCOL COPY DUPLICATE MOVE LOCK UNLOCK OPTIONS HEAD>
         AuthType Basic
         AuthName "floccus"
         AuthUserFile /etc/apache2/.htpasswd_webdav
         Require valid-user
      </Limit>
   </Location>
</VirtualHost>
```

Do you have any recommendations on how WebDAV should be configured for floccus with Apache 2.4.

**Comment by bhlevca** [comment] 2021-02-10 04:52
> @bhlevca [...]  Initial sync with the bookmarks app is usually slower than normal, but subsequent syncs should be quite fast.

Unfortunately, there is something wrong somewhere, the sync is not working at all. In Firefox I monitored with the task manager and floccus has barely any activity. It may be my nextcloud server, which resides on a raspberry pi 4? However, the file synchronisation works just fine and floccus was performing well before with the same configuration. I tried with WebDAV and Bookmarks app none of them works, not in chrome nor in firefox, and I don't know why. It just sits there and does nothing. I removed the bookmarks from the browser and I tried to sync from the App, but it did not work either.  I will put it to rest for a while as I don't have the time to investigate now.  
For the next while, I will use for the sync provided by the browser for now even if this means that Firefox and Brave/Chrome will not have a common repository.

**Comment by marcelklehr** [comment] 2021-02-10 12:33
@truegreyhound I don't have much experience in hosting a WebDAV server. Would you mind adding your config to the wiki, so other people can benefit? :)

**Comment by deragon** [comment] 2021-05-01 20:16
@marcelklehr, following is my config for a Webdav.  The problem is specific to Floccus.  If I use Nautilus to copy/create file on that Webdav, all works fine.

```
  <VirtualHost *:443>
  <...skipped lines...>

  Alias /floccus "${HD_WEBDAV}/sync/browser/floccus/"
  <Directory "${HD_WEBDAV}/sync/browser/floccus/">
    DAV On
    AuthType Basic
    AuthName "floccus"
    AuthUserFile "${HD_WEBDAV}/passwd.dav"
    Require valid-user
  </Directory>
```

**Comment by deragon** [comment] 2021-05-01 20:35
Found the problem, at least for me.  I added `Options -MultiViews` to the <Directory> block.  Following, the full configuration.  Upload worked, but download got HTML parse error.  Investigating...

```
  <VirtualHost *:443>
  <...skipped lines...>

  Alias /floccus "${HD_WEBDAV}/sync/browser/floccus/"
  <Directory "${HD_WEBDAV}/sync/browser/floccus/">
    Options -MultiViews
    DAV On
    AuthType Basic
    AuthName "floccus"
    AuthUserFile "${HD_WEBDAV}/passwd.dav"
    Require valid-user
  </Directory>
```

**Comment by marcelklehr** [comment] 2021-05-03 13:55
Debugging network traffic from the addon may help:

#### Firefox
* Go to `about:debugging`
* click on `debug` button next to floccus entry
* go to the network tab in the inspector tab
* trigger a sync by clicking on `sync now` for the account of your choice.
* check the failing network requests

#### Chrome
* Go to `chrome://extensions`
* enable `Developer mode`
* click on `dist/html/background.html` button in floccus' entry next to "Inspect views: "
* go to the network tab in the inspector window
* trigger a sync by clicking on `sync now` for the account of your choice
* check the failing network requests

**Comment by marcelklehr** [comment] 2021-05-03 13:56
If you get this to work, it'd be cool to have a tutorial or at least your config in the wiki. :)

**Comment by marcelklehr** [comment] 2021-08-13 13:32
@deragon Any news?

**Comment by deragon** [comment] 2021-08-14 19:38
I got it to work somewhere in may.  Currently I am on vacation so I cannot look this up.  But when I return, I will check to see what I have done and report here.  Sorry for having not responded earlier.

**Comment by marcelklehr** [comment] 2021-11-02 12:05
bump @deragon

**Comment by deragon** [comment] 2021-11-13 15:58
Very sorry for the very late response.  Following, the configuration that works 100% for me on my Apache 2.4.41-4ubuntu3.6 HTTP server.  Now everything works fine.

    Alias /floccus "${HD_WEBDAV}/sync/browser/floccus/"
    <Directory "${HD_WEBDAV}/sync/browser/floccus/">
      Options +FollowSymLinks -MultiViews +Indexes +Includes
      DAV On
      AuthType Basic
      AuthName "floccus"
      AuthUserFile "${HD_WEBDAV}/passwd.dav"
      Require valid-user
    </Directory>

**Closed** 2021-11-13 16:20 UTC
Labels: bug, waiting for more information
