### ISSUE TITLE
This profile will be synced soon. We're either waiting for other devices of yours, or other profiles on this device, to finish syncing.

### ISSUE THREAD

**Issue by WantChane** [floccusaddon/floccus#1497] opened 2023-12-26 12:15 UTC
### Which version of floccus are you using?

5.0.4

### Sync method

WebDAV

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

edge 

### What kind of WebDAV server are you using? (if relevant)

https://dav.jianguoyun.com/dav/

### Describe the Bug

can not sync

### Expected Behavior

In the latest version of floccus (in 5.0.5), the prompt "This profile will be synced soon. We're either waiting for other devices of yours, or other profiles on this device, to finish syncing."，however in other versions, e.g. 5.0.4, 4.19.1, he just repeatedly tries to synchronize and eventually fails

### To Reproduce

![image](https://github.com/floccusaddon/floccus/assets/143467549/e443568d-c4c4-4006-ae51-0a0ade6029d9)

### Debug log provided

- [ ] I have provided a debug log file

**Comment by jdelker** [comment] 2023-12-27 11:41
I can confirm this problem with 5.0.5 (currently on Firefox 115.6.0esr) and Nextcloud-Backend via WebDAV.

The sync seems permanently blocked, due to an existing lock.
Bad: Although no sync is performed, the plugin icon shows the "all-ok" checkmark symbol. Thus, this situation remained unnoticed for some time already.

Looking at the access logs on the Nexcloud server, I see continuous tries of the client to receive a lock, each responded with a code 423 error:
```
"POST /index.php/apps/bookmarks/public/rest/v2/lock HTTP/1.1" 423
```
I tried to manually remove the lock with
```
curl -X DELETE -u <user> https://my.nextcloud.server/index.php/apps/bookmarks/public/rest/v2/lock
```
which resulted in the sync to start again.
The client performs a successful lock
```
"POST /index.php/apps/bookmarks/public/rest/v2/lock HTTP/1.1" 200
```
followed by about 50 GETs on various "/index.php/apps/bookmarks/public/..." URLs:
```
"GET /index.php/apps/bookmarks/public/rest/v2/folder/-1/hash HTTP/1.1" 200
"GET /index.php/apps/bookmarks/public/rest/v2/folder?root=-1&layers=0 HTTP/1.1" 200
"GET /index.php/apps/bookmarks/public/rest/v2/folder/1/hash HTTP/1.1" 200
"GET /index.php/apps/bookmarks/public/rest/v2/folder/1/children?layers=1 HTTP/1.1" 200
"GET /index.php/apps/bookmarks/public/rest/v2/folder/494/hash HTTP/1.1" 200
"GET /index.php/apps/bookmarks/public/rest/v2/folder/198/hash HTTP/1.1" 200
...
```
(Not sure, if that is an adequate number for >1k bookmarks)

Then suddenly (4sec after the last GET), the client sends another POST on the lock:
```
"POST /index.php/apps/bookmarks/public/rest/v2/lock HTTP/1.1" 423
```
which is again blocked with code 423.
Now the client is back in the same situation as before.

NOTE: The above was observed with no interference of other Floccus clients. All requests originated from a single client.

**Comment by marcelklehr** [comment] 2023-12-27 11:50
This is a duplicate of #1495

**Closed by marcelklehr** 2023-12-27 11:50 UTC
Labels: bug
