### ISSUE TITLE
Google Drive initial connectivity crashes Edge 93.0.961.38 on macOS Big Sur

### ISSUE THREAD

**Issue by Cakehole** [floccusaddon/floccus#953] opened 2021-09-09 01:01 UTC
### Describe the bug
Cannot establish floccus sync in Microsoft Edge on macOS - Initial login keeps crashing browser

### To Reproduce
1. Added v4.7 extension to Chrome 92.0.4515.159 and Edge 93.0.961.38 on macOS Big Sur 11.5.2
2. Configured Chrome extension first, setting sync to Google Drive - SUCCESSFUL
3. Tried several times to connect extension in Edge to my Google Drive account and browser continues to crash each time I click on 'LOGIN WITH GOOGLE'
4. Tried deleting account and re-adding, but no luck - Log attached

### Expected behavior
Edge successfully connects to Google Drive and sync's to xbel file created by Chrome sync

### Screenshots
[Screen Shot 2021-09-09 at 10 56 05 am](https://user-images.githubusercontent.com/22850721/132604757-c5067fba-e537-4516-b85b-22c623a1951a.png)

### Desktop
 - OS: macOS Big Sur 11.5.2
 - Browser: Chrome / Edge Chromium
 - Browser Version: 92.0.4515.159 / 93.0.961.38
 - Floccus version: 4.7
 - Floccus sync method: Google Drive

### Server
N/A

### Debug log
[floccus-4.7.0-2021-09-09.log](https://github.com/floccusaddon/floccus/files/7132544/floccus-4.7.0-2021-09-09.log)

### Additional context
Happy to donate once I can get this working! Let me know if any issues with what I sent or you need further info - cameron@cakehole.com

**Comment by mnalis** [comment] 2021-09-09 02:41
Likely a bug in Edge to be fixed in `v93`, see https://github.com/floccusaddon/floccus/issues/919

**Comment by marcelklehr** [comment] 2021-09-10 08:39
This is indeed a duplicate of #919 however, Edge 93.0.961.38 is newer than what I used to reproduce last time :/

**Closed by marcelklehr** 2021-09-10 08:39 UTC
Labels: bug

**Comment by marcelklehr** [comment] 2021-09-10 10:20
@all-contributors please add @mnalis for ideas, question and bug

**Comment by marcelklehr** [comment] 2021-09-10 10:22
@all-contributors please add @mnalis for ideas, question and bug
