### ISSUE TITLE
Gdrive login not working on kiwi browser

### ISSUE THREAD

**Issue by Dark-Matter7232** [floccusaddon/floccus#942] opened 2021-08-17 10:49 UTC
### Describe the bug
```Login with Google``` toggle is not working with kiwi browser(uodated to 93.0), clicking on the button does nothing.

### To Reproduce
1. Go to 'Flocuss extension configuration page'
2. Click on 'Login with google'
4. No action

### Expected behavior
Open a page to login with my Google account

### Screenshots
Screenshot of issue
![Screenshot_20210817-161601_Kiwi Browser](https://user-images.githubusercontent.com/38481036/129712803-f445e309-e5dd-4385-ace0-9b8205aefba1.jpg)

### Desktop
 - OS: [Android 12]
 - Browser [Kiwi Browser]
 - Browser Version [93.0.4577.39]
 - Floccus version: [4.7.0]
 - Floccus sync method: [google drive]

**Comment by marcelklehr** [comment] 2021-08-18 13:18
Duplicate of #921

**Closed by marcelklehr** 2021-08-18 13:18 UTC
Labels: bug
