### ISSUE TITLE
can not add a google drive account in mobile browser kiwi

### ISSUE THREAD

**Issue by TujinLee** [floccusaddon/floccus#989] opened 2021-11-02 13:51 UTC
### Desktop
(please complete the following information)
 - OS: andriod/miui12
 - Browser kiwi
 - Browser Version chrome 94
 - Floccus version: 4.83
 - Floccus sync method: clicking the button "login with google" has not responed

### Server
(please complete the following information)
 - OS: [e.g. centOS 7]
 - Nextcloud version: [if applicable]
 - Bookmarks app version: [if applicable]

Note: Please write down the actual version numbers instead of writing 'latest'.

### Debug log
It is often useful to provide a debug log file along with the issue. You can obtain a debug log of the most recent sync runs by clicking 'Debug log' in the bottom right corner of the floccus panel in your browser.

Note: As your debug log usually contains large parts of your bookmark data, instead of attaching it publicly to the issue here, I recommend uploading it privately at the following URL https://cloud.marcelklehr.de/s/PCi3iLWrzdMZSmw

- [ ] Debug log provided

**Comment by marcelklehr** [comment] 2021-11-02 13:58
Duplicate of #921

**Closed by marcelklehr** 2021-11-02 13:58 UTC
Labels: bug

**Comment by TujinLee** [comment] 2021-11-02 15:30
> Duplicate of #921

it has the same problem in mobile phone  browser **yandex**  too.

**Comment by marcelklehr** [comment] 2021-11-02 16:43
> it has the same problem in mobile phone browser yandex too.

this does not mean that it's necessarily an issue with floccus. If you have insights about this, provide them at the issue linked above

**Comment by Iangh59** [comment] 2021-11-06 00:11
Similar in Firefox nightly in that I can see the account options but clicking Google nothing happens, no forwarding to Google account page. On Kiwi can get to account page.

Working wonderfully on desktop browsers, thank you.

**Comment by marcelklehr** [comment] 2021-11-10 15:04
> Similar in Firefox nightly

Firefox for android is not supported at all, due to their lack of web extension API support.

**Comment by Iangh59** [comment] 2021-11-10 17:49
The workaround is to get floccus working on a desktop and then export the account. I haven't tried it with FF nightly but it certainly works with Kiwi, https://www.reddit.com/r/kiwibrowser/comments/qozcww/comment/hjqcu07/?utm_source=share&utm_medium=web2x&context=3.
