### ISSUE TITLE
Initial connect to Google doesn't work 

### ISSUE THREAD

**Issue by thembuck** [floccusaddon/floccus#1237] opened 2022-08-13 12:10 UTC
### Which version of floccus are you using?

4.17

### Sync method

Google Drive

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Android 11 Redme 9s

### Describe the Bug

After selecting the account I get logged in and google search opens. From there I can't get back to floccus app in a connected state 

### Expected Behavior

Floccus is connected and the actual sync can be configured 

### To Reproduce

Start the app for the first time, try to connect to Google, become stuck 
Easy for me, but probably hard for you.

### Debug log provided

- [ ] I have provided a debug log file

**Comment by marcelklehr** [comment] 2022-09-04 13:59
Thanks for reporting, this should be fixed by #1246

**Comment by marcelklehr** [comment] 2022-09-17 19:25
*@thembuck wrote*

---

After selecting the account I get logged in and google search opens. From there I can't get back to floccus app in a connected state.

4.17.1 form f- droid didn't change that behavior.

4.17.0 worked well on a different device (android 8) with a different google account.

**Comment by marcelklehr** [comment] 2022-09-17 19:26
mmh, this is weird. Are you sure that you have installed v4.17.1? Simply installing in the F-Droid app without updating from the F-Droid repository sometimes doesn't give you the latest version.

**Comment by thembuck** [comment] 2022-09-17 19:42
Hey Marcel,

App-info in Android settings says it's 4.17.1.


I can't verify form within the app, since I'm stuck in the connection step.  It seems there is no app menu until connected.

I have a working connection form my desktop pc using the browser plugin on my main googl account. Sync is working between two different  desktop browsers.

The app (even 4.17.0) did work on an other mobile device with an older android version although I used a a different google account there.

Thank you for your support.

----------------------------------------

17.09.2022 21:26:55 Marcel Klehr ***@***.***>:

**Comment by Tamaya-Jin** [comment] 2022-10-04 16:54
Same problem!
But the Android version is different.

**Which version of floccus are you using?**
4.17.0

**Sync method**
Google Drive

**Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.**
Android 12 
Samsung Galaxy Note10 Lite

**Describe the Bug**
Logging in Google account and getting the bookmarks file are successful, but it can't sync and showed E017.

**Expected Behavior**
Connection and sync are successful

**To Reproduce**
I have been using this App since it was released. But one day, it couldn't work suddenly. I try the method that writing in "Describe the Bug" many times but it never works.

**Comment by thembuck** [comment] 2022-10-16 20:53
I checked it out today again and guess what...it works now.
Google asks for second factor and in I am.
So let's close this issue.

**Comment by thembuck** [comment] 2022-10-16 20:54
See above.

**Closed** 2022-10-17 08:57 UTC
Labels: bug
