### ISSUE TITLE
Can't login with google on kiwi

### ISSUE THREAD

**Issue by badochov** [floccusaddon/floccus#948] opened 2021-08-30 21:20 UTC
### Describe the bug
Clicking login with the google button doesn't have any effect on the kiwi browser.
I checked the console but it's clear. I might dig into it tomorrow.

### To Reproduce
1. Try to add a Google account
2. Click "Login with Google" button

### Expected behavior
Google authentication website should open.

### Desktop
(please complete the following information)
 - OS: Android
 - Browser Kiwi
 - Browser Version 93.0.4577.39
 - Floccus version: 4.7.0
 - Floccus sync method: google drive

**Comment by marcelklehr** [comment] 2021-08-31 04:41
duplicate of #285

**Closed by marcelklehr** 2021-08-31 04:41 UTC
Labels: bug

**Comment by badochov** [comment] 2021-08-31 05:59
Imho its not duplicate. I can do anything but login with google and kiwi doesn't crash.

**Comment by marcelklehr** [comment] 2021-08-31 06:03
My bad, I linked the wrong issue.
