### ISSUE TITLE
Sync interval not saved

### ISSUE THREAD

**Issue by vaini** [floccusaddon/floccus#1414] opened 2023-09-29 19:32 UTC
### Which version of floccus are you using?

4.19.1

### Sync method

Google Drive

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Firefox v118.0.1 and Microsoft Edge Canary v119.0.2129.0

### Describe the Bug

Does not record sync interval change from 15 to 5 minutes

### Expected Behavior

The change is stored.

### To Reproduce

1. Click on the Floccus icon;
2. Click the down arrow for more options;
3. Click on the gear icon (Options);
4. Click on "Sync behavior";
5. In "Sync Interval" change it to 5 minutes (slide);
6. Scroll the page to the end;
7. Click "Save"

Following these steps, a green sign appears, indicating that the change has been saved, however, when opening the settings screen again, or even restarting the browser, the synchronization interval returns to 15 minutes. The same thing happens in the two browsers I used.

### Debug log provided

- [ ] I have provided a debug log file

**Comment by Rami-Ha** [comment] 2023-10-17 18:55
I'm having the same problem

**Comment by RealStickman** [comment] 2023-11-02 17:59
I'm also having this issue. Even with a new account, setting the sync interval to 5 minutes doesn't work.  

Setting 10 minutes or any greater interval (that I tested) does stick, it appears to be specific to the 5 minutes duration where it will be reset to 15 minutes.  
With the 10 minute interval set, it did indeed start a sync about 10 minutes (11 shown in UI) after the previous one.  

I couldn't find anything useful in the debug files (redacted or full) searching for words like sync, interval, duration etc. that would give further hints.

For my environment, I'm using Nextcloud 25.13. Freshly set up Floccus today for the first time on two devices (Linux and Windows), both with Firefox 119.

**Comment by kolinger** [comment] 2023-11-27 12:32
This issue is duplicate of #1310 that was fixed but not really.

**Closed** 2023-12-06 19:09 UTC
Labels: bug
