### ISSUE TITLE
Floccus bookmarks sync plugin does not work synchronization with google drive in kiwi browser

### ISSUE THREAD

**Issue by vldanch** [floccusaddon/floccus#1221] opened 2022-07-24 08:02 UTC
When adding a new account, choose `google drive`, click on `login with google`, nothing happens...   
Link to plugin: https://chrome.google.com/webstore/detail/floccus-bookmarks-sync/fnaicdffflnofjppbagibeoednhnbjhg?hl=en
Browser: https://kiwibrowser.com/

**Comment by pinpontitit** [comment] 2022-07-25 00:32
Could be related with my issue #1220.
I just tried with Android and it works. 
I'll download Kiwi browser tomorrow to see if I can reproduce.
Which version of kiwi are you using ?

**Comment by vldanch** [comment] 2022-07-25 18:36
@pinpontitit Kiwi Browser: `101.0.4951.48`
At the moment this version.

**Comment by pinpontitit** [comment] 2022-07-25 21:48
Wtf, I didnt know Kiwi browser was an Android browser. I was thinking you were speaking about desktop.

However I tried anyway to download Kiwi with floccus extension and, you're right, the button doesnt work. Exactly the same behavior as in the iOS app.

My advice:
you could try creating an account on desktop with another browser,
then on Floccus settings you click on exporting the account
and then, when you come back in Kiwi browser, instead of "Login with Google",  you click on Importing an account, and you import the account you exported earlier.

tell me if it works.

However I'm surprised: why do you want to use Floccus with Kiwi browser, instead of using Floccus app from the "Play Store" or better from "F-Droid", that works flawlessly ? 
(Thats a true question, I think I saw in this github a lot of people speaking about kiwi browser, Is it because you all are rooted or can't use F-Droid, or something else ?)

**Comment by pinpontitit** [comment] 2022-07-25 21:55
Ok so I discovered that your problem is already known and was already reported [here](https://github.com/floccusaddon/floccus/issues/921).

It seems the problem comes from Kiwi browser and the dev is already aware and trying to fix that.

However would you accept to answer me ?
Why is it so useful to use Kiwi with floccus extension instead of Floccus app ?

**Comment by pinpontitit** [comment] 2022-07-25 21:58
It also seems that the solution I described to you above works:
[https://github.com/floccusaddon/floccus/issues/921#issuecomment-1139283098](https://github.com/floccusaddon/floccus/issues/921#issuecomment-1139283098)

**Comment by marcelklehr** [comment] 2022-08-04 12:57
Closing as duplicate of #921 

Thank you for triageing @pinpontitit

**Closed by marcelklehr** 2022-08-04 12:57 UTC
