### ISSUE TITLE
too many .xbel files created on Google Drive

### ISSUE THREAD

**Issue by cimenta** [floccusaddon/floccus#1652] opened 2024-06-18 06:26 UTC
### Which version of floccus are you using?

5.2.1

### How many bookmarks do you have, roughly?

2000

### Are you using other means to sync bookmarks in parallel to floccus?

no

### Sync method

Google Drive

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

firefox, Brave, Chrome, Vivaldi

### Describe the Bug

hi
on my Google Driver I got 88 floccus-bookmars.xbel files. They are created almost every day.

![image](https://github.com/floccusaddon/floccus/assets/1837850/e0422c73-244b-40e5-aa13-dccf4fc5d971)

can you please have a look into it?

Thank you
Radek

### Expected Behavior

just one .xbel file

### To Reproduce

Not sure about the steps to reproduce. I installed floccus and have been using it. I do not think I did anything "special".

Sync between all 4 browsers I am using is working fine.

### Debug log provided

- [ ] I have provided a debug log file

**Comment by marcelklehr** [comment] 2024-06-20 15:27
Hello Radek

When did you start using Floccus with Google Drive and when did the second file appear?

**Comment by cimenta** [comment] 2024-06-20 16:29
hi Marcel

- I have using floccus for a year or two.
- it seems to me that the issue of creating another copies of .xbel file started on 7. 5. 2024 But I will try to double check
![image](https://github.com/floccusaddon/floccus/assets/1837850/d228c427-1a9c-4b7e-8c5b-3e8831f74101)

**Comment by cimenta** [comment] 2024-06-20 16:40
yes, 

- It looks like the issues started on 7.5. 2024.
- currently I got 90 files and counting ....
![image](https://github.com/floccusaddon/floccus/assets/1837850/682be74d-3b04-459b-b75c-141acaf979e8)

**Comment by marcelklehr** [comment] 2024-07-02 17:31
Do you use floccus also via the mobile app?

**Comment by cimenta** [comment] 2024-07-02 17:51
Never tried
Radek

**Comment by marcelklehr** [comment] 2024-07-05 11:21
What is your sync interval?

**Comment by marcelklehr** [comment] 2024-07-05 12:59
Can you try to identify one of the browsers that might be causing this, perhaps?

**Comment by marcelklehr** [comment] 2024-07-05 13:01
@teodias requests a cleaning routine for the excess xbel files

**Comment by marcelklehr** [comment] 2024-07-06 09:14
Which strategy are you syncing with?

**Comment by cimenta** [comment] 2024-07-09 09:45
> What is your sync interval?

now 5 mins but used to be the default 15 mins

I do not think it matters. it definitely started when it was 15. Continues when it is 5 mins

**Comment by cimenta** [comment] 2024-07-09 09:51
> Can you try to identify one of the browsers that might be causing this, perhaps?

not sure how to identify ....

**Comment by marcelklehr** [comment] 2024-07-18 14:17
> > Can you try to identify one of the browsers that might be causing this, perhaps?
> not sure how to identify ....

You can try disabling the extension on one of the browsers for a few days and see if that fixes it

**Comment by cimenta** [comment] 2024-07-20 08:16
> > > Can you try to identify one of the browsers that might be causing this, perhaps?
> > > not sure how to identify ....
> 
> You can try disabling the extension on one of the browsers for a few days and see if that fixes it

ok, I stopped auto-sync for all browsers but Firefox ..

**Comment by cimenta** [comment] 2024-07-22 08:24
hi
so 2 days ago I disabled fluccus sync of all browses but firefox. And today I have new .xbel file on my Google drive.

**Comment by marcelklehr** [comment] 2024-07-22 08:58
Awesome, thank you for that. Can you try disabling firefox and enabling some other browser?

**Comment by cimenta** [comment] 2024-07-22 09:09
hi Marcel

1. I disabled syncing in ff
2. enabled syncing in chrome
3. bookmarks were synced to chrome correctly
4. and also the .bel file in Google drive got updated. New one was not created.

I will update this ticket in a few days with my observations

Thank you
Radek

**Comment by cimenta** [comment] 2024-07-28 07:05
So after 6 days of using just Chrome it seems to me that everything is ok

![image](https://github.com/user-attachments/assets/997c59a1-2d44-44b1-9697-987184eb49d1)

Just the last .xbel is updated.

I am going to turn on syncing in firefox.

Radek

**Comment by marcelklehr** [comment] 2024-07-28 10:33
Interesting. So it seems firefox is the problem then. Or perhaps this was resolved with the latest update, that would be even better.

**Comment by namadori** [comment] 2024-07-30 07:56
I have the same issue, new files created randomly every few days or even multiple times a day.
I am using v5.2.5 on Chrome on Windows, Chrome on MacOs (but only in the weekend) and Android app. I was using Firefox but stopped some months ago.

I've been out of office for a week and no files were created, so I suspect that the Windows Chrome extension is making them.

I am still confused how Google Drive allows to have many files with the same name in the same folder. I noticed that the files are not created with the final name, but rather uploaded as "untitled", renamed and then edited a number of times, until a new file is created.

![image](https://github.com/user-attachments/assets/6ebce055-9704-47c0-9fc9-5efec25cc249)

**Comment by marcelklehr** [comment] 2024-07-30 14:03
@namadori Anything after July 26 ?

**Comment by namadori** [comment] 2024-07-30 19:51
Too early to say, but maybe...

Couple of files on the 27th, then the PC was shut down during the weekend. The last 2 files created on the 27th are currently being updated, and no new files were created yesterday or today.

I'll look again in a couple of days, if will be no new files I think the issue is solved. Great timing :-)

**Comment by cimenta** [comment] 2024-07-31 05:40
> So after 6 days of using just Chrome it seems to me that everything is ok
> 
> ![image](https://private-user-images.githubusercontent.com/1837850/352795126-997c59a1-2d44-44b1-9697-987184eb49d1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0MDQ1ODMsIm5iZiI6MTcyMjQwNDI4MywicGF0aCI6Ii8xODM3ODUwLzM1Mjc5NTEyNi05OTdjNTlhMS0yZDQ0LTQ0YjEtOTY5Ny05ODcxODRlYjQ5ZDEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDczMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MzFUMDUzODAzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzE1NzhkNjY2Zjc0OGRlMTllZmU5YzAzM2U2NWU5OWNjZDU1YmY5ZmI2YjA3MTQ1MzUwMmYwMWRiZjI5MGIxYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.evGE6Z7f0wl38-_E_kR3MS4fqg-wZpZ9blloTl9uyD8)
> 
> Just the last .xbel is updated.
> 
> I am going to turn on syncing in firefox.
> 
> Radek

nothing changed for me after I started to use firefox, I will wait for few more days and then introduce Vivaldi or Brave

![image](https://github.com/user-attachments/assets/d7f53353-0f9c-47af-883e-adafdf014658)

**Comment by marcelklehr** [comment] 2024-08-11 08:39
Any news here? Did you get more excess files even with v5.2.5?

**Comment by cimenta** [comment] 2024-08-11 12:09
looks good to me

![image](https://github.com/user-attachments/assets/96adc465-10ae-4d41-887e-7a2c88c543b2)

I am going to start using Brave

**Comment by namadori** [comment] 2024-08-14 16:59
The issue solved on Jul 27 for me, no more files created since then. Thanks for your support.

**Comment by ValuableIdeas** [comment] 2024-09-09 11:06
Hello,
I use Google Drive as sync method, and I have the same issue, which hasn't been resolved despite v5.2.5 at the end of July.
I'm currently using version 5.2.7 with Chrome (128.0.6613.120) and Firefox (130.0) on Windows, and the Android app v5.2.6 with Android 12.
I'm syncing two xbel files and they both have this problem.
![Capture bookmarks](https://github.com/user-attachments/assets/1d033d94-c4d8-47dd-87f4-2b1246095624)

**Comment by cimenta** [comment] 2024-09-09 19:25
I checked again... it looks like the issue was not solved. It is much better but I do have some duplicates. Not so many though

![image](https://github.com/user-attachments/assets/5facd62c-bd0e-47bb-809f-8af9d3231151)

**Comment by marcelklehr** [comment] 2024-09-10 09:21
Could you check the history of the most recently updated file, to see if it's new or has been modified before?

**Comment by cimenta** [comment] 2024-09-10 13:23
![image](https://github.com/user-attachments/assets/b6cfc2ac-9771-46de-bee2-b7b9783ee00d)

and it starts like this 
![image](https://github.com/user-attachments/assets/fad23488-fe34-42e2-8ff6-da4f28e9a6c9)

**Comment by ValuableIdeas** [comment] 2024-09-10 19:02
I have the same file history scheme as cimenta.
![image](https://github.com/user-attachments/assets/a2832544-7377-4308-ac6d-a4032f1e2b8e)

**Comment by marcelklehr** [comment] 2024-09-12 14:10
Aha, and what about the other files do they have multiple edits to them as well?

**Comment by ValuableIdeas** [comment] 2024-09-12 15:46
Yes, other files also have multiple edits.
In the history of each file, the first entry (‘you uploaded an item’) corresponds in date and time to the last modification of the previous file, so it's probably this one which has been uploaded and then modified.

**Comment by ChrisCh7** [comment] 2024-10-01 16:19
Still happening after the most recent update.
There was a single xbel file, it updated it and at the same time it created a new file with the same name and continued to update that instead after that.

**Comment by marcelklehr** [comment] 2024-10-09 11:29
v5.3.1 is out now with a mechanism to at least remove all remnant xbel files, if we can't prevent them from being created. Let me know how it goes. :)

**Comment by ValuableIdeas** [comment] 2024-10-09 19:16
I updated and all the old files magically disappeared! Thanks a lot Marcel :)

**Comment by marcelklehr** [comment] 2024-10-20 09:49
Closing for now.

**Closed by marcelklehr** 2024-10-20 09:49 UTC
Labels: bug, waiting for more information, priority: high
