### ISSUE TITLE
Losing changes while syncing

### ISSUE THREAD

**Issue by nikolausmoll** [floccusaddon/floccus#1142] opened 2022-04-26 22:03 UTC
### Which version of floccus are you using?

4.13.1

### Sync method

{"label"=>"Nextcloud Bookmarks"}

### Which browser are you using?

Firefox 99.0.1 (64-Bit)

### Which version of Nextcloud Bookmarks are you using? (if relevant)

10.3.1

### Which version of Nextcloud? (if relevant)

23.0.4

### Describe the Bug

I am syncing many bookmarks with NextCloud, and the two-way-sync (merge local & cloud) takes quite some time then (10-15 seconds). 
The browser plugin seems to start the sync after each change like renaming a single bookmark, that is kinda new behaviour for me and I am not used to it, don't know since which version the plugin does this.

But the problem with this is, when I change one bookmark and I ignore that the sync is running, and I keep changing other bookmarks, the changes after the sync has started will be reverted due to the sync. And that is really stupid, because 
a) I have to wait and wait and wait to manage the bookmarks (and I don't want to stop syncing during the changes, the addon shall support me and not define how I have to do my work)
b) the progress icon for the sync is not soo different comapred to the normal one so I really have to look exactly at it to see if a sync is in progress

### Expected Behavior

I do not want to lose my new changes made after the sync has started.

### To Reproduce

- Many bookmarks to sync, so sync takes a couple of time
- Change a single bookmark (A)
- Ensure syncing starts (Merge local & cload)
- Change another bookmark (B)
- Wait till syncing has finished
- B should now be reverted to its earlier state

### Debug log provided

- [ ] I have provided a debug log file

**Comment by marcelklehr** [comment] 2022-04-29 12:28
Duplicate of #1088

Will be resolved next release

**Closed by marcelklehr** 2022-04-29 12:28 UTC
Labels: bug
