### ISSUE TITLE
E017: Network Error on Android App  Floccus 5.0.2

### ISSUE THREAD

**Issue by Morethanevil** [floccusaddon/floccus#1459] opened 2023-12-11 04:50 UTC
### Which version of floccus are you using?

5.0.2 F-Droid release

### Sync method

WebDAV

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

Android 13 Oneplus 9 Pro

### Which version of Nextcloud? (if relevant)

27.4

### Describe the Bug

Everytime i get error 17 when i press sync. i tried to reset the app completely, still the same issue. Happened after updating to release v5. Thought it would be fixed now, but still the same

### Expected Behavior

Sync works

### To Reproduce

Update from v4.19 to latest release and get the error

Firefox extensions works without problems.

### Debug log provided

- [X] I have provided a debug log file

**Comment by marcelklehr** [comment] 2023-12-11 07:47
This is a duplicate of #1455

**Closed by marcelklehr** 2023-12-11 07:47 UTC
Labels: bug
