### ISSUE TITLE
Music stops when open iOS app

### ISSUE THREAD

**Issue by ckykenken** [floccusaddon/floccus#1336] opened 2023-02-08 00:53 UTC
### Which version of floccus are you using?

4.17.0

### Sync method

WebDAV

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

iOS 16.2

### Describe the Bug

Whenever I open the Floccus app when Apple Music is playing music, the music stops.

### Expected Behavior

The music should keep playing when opening the Floccus app

### To Reproduce

1. Open any music app (e.g. Spotify, Apple Music… you name it) and play some music
2. Open Floccus app or switch into it

### Debug log provided

- [ ] I have provided a debug log file

**Comment by marcelklehr** [comment] 2023-12-06 18:54
This appears to be a duplicate of #1239 -- please shout here if you feel this is an error, but I am closing this as a duplicate.

**Closed by marcelklehr** 2023-12-06 18:54 UTC
Labels: bug
