### ISSUE TITLE
This profile will be synced soon. We're either waiting for other devices of yours, or other profiles on this device, to finish syncing.

### ISSUE THREAD

**Issue by lsh1215225** [floccusaddon/floccus#1559] opened 2024-03-12 09:04 UTC
### Which version of floccus are you using?

5.0.9

### Sync method

WebDAV

### Which browser are you using? In case you are using the phone App, specify the Android or iOS version and device please.

chrome release latest

### What kind of WebDAV server are you using? (if relevant)

infinicloud

### Describe the Bug

When I sync the same account on more than 3 devices, it shows on Mac that this profile will be synced soon. We're either waiting for other devices of yours, or other profiles on this device, to finish syncing.

### Expected Behavior

sync succeed

### To Reproduce

I cant reproduce it now, because i remove the account and create a new one. Then I was surprised to find that the problem was solved, as long as it is set like in the picture.
<img width="578" alt="image" src="https://github.com/floccusaddon/floccus/assets/20274559/a8875f91-8905-4931-8f75-7d01ecfca42d">

### Debug log provided

- [ ] I have provided a debug log file

**Comment by marcelklehr** [comment] 2024-03-12 17:03
Hi! I think this is a duplicate of https://github.com/floccusaddon/floccus/issues/1548

**Closed by marcelklehr** 2024-03-12 17:03 UTC
Labels: bug
