### ISSUE TITLE
Sync problems on macos

### ISSUE THREAD

**Issue by donotos** [floccusaddon/floccus#950] opened 2021-09-03 11:15 UTC
### Describe the bug
When syncing i get E017 or E020 Error
first i got the E020, then after a couple of days it became E017. Afler deleting the extension settings and recreating the account it goes back to E020

### To Reproduce
try to sync bookmarks

### Expected behavior
Should sync

### Desktop
(please complete the following information)
 - OS: MacOS 11.0.1
 - Browser 1: Vivaldi - v4.1.2369.21
 - Browser 2: Brave - Version 1.29.76 Chromium: 93.0.4577.58
 - Floccus version: 4.7.0
 - Floccus sync method: nextcloud bookmarks

### Server
 - OS: Debian 10
 - Nextcloud version: 21.0.3
 - Bookmarks app version: 4.4.1

### Debug log
- 000028.log

### Additional context
i use two browsers and both are impacted
my nextcloud is hosted on yunohost
the problem is only on mac. my windows pc sync without issues.
it worked well fo months without issues, the problem only started afterward without any changes (no updates or anything)
to diagnose i installed another nextcloud with docker without ssl. it sync without issues on that server (see log)

**Comment by marcelklehr** [comment] 2021-09-03 11:39
Hi @donotos
Thank you for your feedback and sorry for your troubles!
I suspect this may be a duplicate of https://github.com/nextcloud/bookmarks/issues/1631, an issue with bookmarks app on yunohost.
Can you confirm this?

**Comment by donotos** [comment] 2021-09-03 12:00
HI.
Is seems to be the same issue, i have the same error in my log:

`{"Exception":"PDOException","Message":"SQLSTATE[HY001]: Memory allocation error: 1038 Out of sort memory, consider increasing server sort buffer size","Code":"HY001","Trace":[{"file":"/var/www/nextcloud/3rdparty/doctrine/dbal/src/Driver/PDO/Statement.php","line":82,"function":"execute","class":"PDOStatement","type":"->","args":[null]}`

**Comment by mnalis** [comment] 2021-09-03 12:45
> then now i'm wondering why is it ok on my windows PC

Error seems to be `out of memory` condition when communicating with SQL server. That would likely happen depending on the (sub)result size of SQL query, which in turn would likely depend (among other things) on how many bookmarks have changed. So, for example, if you sync more often, the chance of problem might be less. (But memory conditions might depend of lots of other factors too).

It seems like Yunohost manually lowered sort_buffer(s) to levels that are now sometimes too low for some applications.

I'm not familiar with Yunohost, but do you have an user interface (like shell, or web-based Adminer or PHPMyAdmin etc.) to send SQL queries on that server? If so, it would be very interesting to know the output of following MySQL query:
``` 
show session variables like "%sort_buffer%";
```

Could you try that, @donotos ?

**Comment by donotos** [comment] 2021-09-03 12:48
Here it is:

+-------------------------+-----------+
| Variable_name           | Value     |
+-------------------------+-----------+
| aria_sort_buffer_size   | 268434432 |
| innodb_sort_buffer_size | 1048576   |
| myisam_sort_buffer_size | 134216704 |
| sort_buffer_size        | 65536     |
+-------------------------+-----------+
4 rows in set (0.444 sec)

**Comment by mnalis** [comment] 2021-09-03 13:33
Thanks! Yes, as I suspected, `sort_buffer_size` is definitely set rather small, just `64K` (smallest [default](https://dev.mysql.com/doc/refman/8.0/en/server-system-variables.html#sysvar_sort_buffer_size) is `256K`).  

I see several possible way around it:
- improve nextcloud bookmark app to detect such condition and try to autorecover from it: eg. on startup after establishing mysql connection it would do `show session variables like "sort_buffer_size"` and if the result is less than `262144` increase it (for that connection) with `set session  sort_buffer_size=262144`. That should hopefully workaround the issue on all servers, and requires very little work, so I think it is best to try - what do you think, @marcelklehr ?
- try to reproduce that problem on MySQL server with small `sort_buffer_size`, and then troubleshoot the query causing problems. The linked issue had only 22 bookmarks, so even smallest sort_buffer should've worked fine really. Maybe the SQL queries get way too complex? From perfectionists point of view, this would be the ideal to fix, but it very likely requires much bigger effort, and the problem might turn out to be mysql server bug not being able to correctly handle such small buffer sizes - which then should be fixed (or minimum buffer size enforced) in mysqld codebase.  
- Contact Yunohost and ask for the [sort buffer to be increased](https://stackoverflow.com/a/29575947/2600099) system-wide, explaining the problem. They might be reluctant to do that though, because the possible maximum memory usage rises linearly with number of active MySQL sessions, and they likely had reasons to reduce it.

**Comment by donotos** [comment] 2021-09-03 14:04
found the issue on yunohost https://github.com/YunoHost/issues/issues/1868
they want to change the conf in the migration to the next major debian version, meaning not anytime soon....
i will snapshot my vm and try to increase the size in mariadb to see what happen.

**Comment by donotos** [comment] 2021-09-03 14:24
That was it! i changed the size in my.cnf (64k > 128k) then restart mariadb, restart browser and it sync!

**Comment by marcelklehr** [comment] 2021-09-03 14:26
@mnalis Thanks for jumping in! I had indeed identified the problematic query and tried to reduce its memory usage. Apparently, now it works when everything is set up, but doesn't on the very first floccus run (likely because floccus fetches all bookmarks in batches of 300 items when nothing has been synced so far). I'll look into this soon.

**Comment by hercut** [comment] 2021-09-10 14:01
Hello, I have the same error with the same configuration.
Yunohost with its last update changed the value of sort_buffer_size by 4M.
But I still have the same problem ...


2021-09-10T13:59:47.870Z Syncing failed with E020: Impossible de lire la réponse du serveur. L'application de marque-pages est elle installée sur votre serveur?
JSON.parse: unexpected character at line 1 column 1 of the JSON data

**Comment by marcelklehr** [comment] 2021-09-10 15:57
@hercut check your nextcloud log for errors, this is the floccus log.

**Comment by donotos** [comment] 2021-09-10 18:11
I just updated yunohost to 4.2.8.3 but there was no change to the sort_buffer_size config i still have 128K.
you can easily check yours by using this in the yunohost shell:
`mysql -u root -e 'show session variables like "%sort_buffer%";'`

**Comment by hercut** [comment] 2021-09-10 18:59
> I just updated yunohost to 4.2.8.3 but there was no change to the sort_buffer_size config i still have 128K.
> you can easily check yours by using this in the yunohost shell:
> `mysql -u root -e 'show session variables like "%sort_buffer%";'`

+-------------------------+-----------+
| Variable_name           | Value     |
+-------------------------+-----------+
| aria_sort_buffer_size   | 268434432 |
| innodb_sort_buffer_size | 1048576   |
| myisam_sort_buffer_size | 134216704 |
| sort_buffer_size        | 4194304   |
+-------------------------+-----------+

**Comment by hercut** [comment] 2021-09-10 19:00
I dont know where i can find log nextcloud :/

**Comment by donotos** [comment] 2021-09-10 19:03
/home/yunohost.app/nextcloud/data/nextcloud.log

**Comment by hercut** [comment] 2021-09-10 19:09
it's possible to DL with terminal ?

**Comment by donotos** [comment] 2021-09-10 19:10
you can use sftp yes with a client like filezilla or winscp

**Comment by hercut** [comment] 2021-09-10 19:31
Grrrr, can't, it say not permission

**Comment by mnalis** [comment] 2021-09-10 23:23
@hercut you should be able to copy it somewhere and give it read permissions:
```
sudo cp /home/yunohost.app/nextcloud/data/nextcloud.log /tmp/nextcloud-copy.log
sudo chmod a+r /tmp/nextcloud-copy.log
```

then you should be able to copy it via scp (remember to remove that copy afterwards)

**Comment by hercut** [comment] 2021-09-11 07:53
Thanks for the tip :)

Voici le log :
https://kpaste.infomaniak.com/cQ3qg1hbqCxxFTL20-Ibw-zmtyNN4Vzi#2UR6KQXCVVXv7xNXgptN85EjeD9XVmZSy4HxDf1rg6rS

**Comment by mnalis** [comment] 2021-09-11 22:38
@hercut this does not look to me as the same issue as @donotos was having - Last occurrence of `Memory allocation error: 1038 Out of sort memory, consider increasing server sort buffer size` in your log I see is several moths ago, at `2021-07-12T14:34:48+00:00`.

It seems you have upgraded nextcloud from 22.0.0.11 to 22.1.1.2 on 2021-09-10, did the floccus work before that?

Also, either time on your computer `2021-09-10T13:59:47.870Z` or time on server are not correct; as server shows no nextcloud activity between `2021-09-10T13:28:39+00:00` and `2021-09-10T14:16:06+00:00`. 
Looking at those after 14:16 GMT, it sound mostly like network issues with cURL trying to access defunct hosts (or browser-specific URLs like `javascript:` or `moz-extension:`).

```
% grep 2021-09-10T14 floccus.log | grep -io -P 'message":".*?("| for )'

message":"cURL error 18: transfer closed with outstanding read data remaining (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for
message":"cURL error 28: Operation timed out after 10001 milliseconds with 0 bytes received (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for
message":"cURL error 6: Could not resolve host: www.teenax.tv (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for
message":"cURL error 28: Resolving timed out after 10000 milliseconds (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for
message":"cURL error 7: Failed to connect to www.mywebftp.com port 80: No route to host (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for
message":"cURL error 3:  (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for
message":"cURL error 3:  (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for
message":"dns_get_record(): A temporary server error occurred. at /var/www/nextcloud/lib/private/Http/Client/DnsPinMiddleware.php#83"
Message":"dns_get_record(): A temporary server error occurred. at /var/www/nextcloud/lib/private/Http/Client/DnsPinMiddleware.php#83"
Message":"--"
message":"cURL error 7: Failed to connect to www.cd-partenaires.com port 443: Connection timed out (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for
message":"cURL error 60: SSL certificate problem: unable to get local issuer certificate (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for
message":"cURL error 6: Could not resolve host: moz-extension (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for
message":"cURL error 6: Could not resolve host: moz-extension (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for
message":"cURL error 28: Resolving timed out after 10000 milliseconds (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for
```

**Comment by hercut** [comment] 2021-09-12 10:16
Thank you for your feedback.
Floccus never worked, I must admit that the bookmark plugin too.
I have bugs with the import of my bookmarks.

In order to make everything work, I started with a clean installation of nextcloud via Yunohost. But it still didn't work.

And here I am trying to understand ...

Should I try again to install all the tools?

**Comment by mnalis** [comment] 2021-09-12 13:24
@hercut I'm not sure what "tools" you want to reinstall (I'm not familiar with Yunohost, though)?

As far as I can tell, Yunohost nextcloud syncing _should work_ now when the sort buffer issue is fixed (eg. when `sort_buffer_size = 4194304` as you showed).

What I would do is:
- make a backup of your bookmarks (always a good idea!)
- delete floccus account in your web browser
- delete all bookmarks in your nextcloud bookmarks app (if any) 
- update floccus to latest version (if needed)
- update nextcloud bookmarks app to latest version (if needed)
- make sure you **don't have any other** [bookmark sync mechanisms](https://floccus.org/faq#i-am-currently-using-a-different-tool-to-sync-my-browser-data-can-i-use-this-with-floccus) enabled (like firefox sync for example) 
- create a new account in floccus (see instructions at https://floccus.org/start)
- wait for floccus to finish syncing (or report error)
- **if it still fails**, open a new GitHub issue, filling out the template with all data it asks for (versions of browser, nextcloud, bookmarks app,  exact error messages, logs etc.)

**Comment by hercut** [comment] 2021-09-13 13:46
Well, it looks like everything is working now.
I reinstalled Nextcloud and floccus.
Everything works ...

Probably with the Yunohost update.

Thanks for your help and sorry for the inconvenience...

**Closed** 2021-09-13 14:29 UTC
Labels: bug
